### PR TITLE
Add double short and byte support to UserData

### PR DESCRIPTION
**Pull request by riccardobl**
Test case
src/test/java/unit/TestUserData.java
```java
package unit;
import com.jme3.scene.Node;
import com.jme3.scene.Spatial;
import org.junit.Test;
import junit.framework.TestCase;
public class TestUserData extends TestCase {

    public static void userDataTest(Spatial sp, Object v) {
        sp.setUserData("test",v);
        assertTrue("UserData is null",sp.getUserData("test")!=null);
        assertEquals("UserData value is different than input value",sp.getUserData("test"),v);
        sp.setUserData("test",null);
    }
    
    @Test
    public void testLong() throws Exception {
        Spatial sp=new Node("TestSpatial");
        userDataTest(sp,(Long)(long)(Math.random()*Long.MAX_VALUE));
    }

    @Test
    public void testInt() throws Exception {
        Spatial sp=new Node("TestSpatial");
        userDataTest(sp,(Integer)(int)(Math.random()*Integer.MAX_VALUE));
    }

    @Test
    public void testShort() throws Exception {
        Spatial sp=new Node("TestSpatial");
        userDataTest(sp,(Short)(short)(Math.random()*Short.MAX_VALUE));
    }

    @Test
    public void testByte() throws Exception {
        Spatial sp=new Node("TestSpatial");
        userDataTest(sp,(Byte)(byte)(Math.random()*Byte.MAX_VALUE));
    }

    @Test
    public void testDouble() throws Exception {
        Spatial sp=new Node("TestSpatial");
        userDataTest(sp,(Double)(double)(Math.random()*Double.MAX_VALUE));
    }

    @Test
    public void testFloat() throws Exception {
        Spatial sp=new Node("TestSpatial");
        userDataTest(sp,(Float)(float)(Math.random()*Float.MAX_VALUE));
    }
}

```

build.gradle
```gradle
apply plugin : 'java' 

// Usage: gradle test

// JME master
// def jmerepo='com.github.jMonkeyEngine.jmonkeyengine'
// def jmeversion='025b27c96d295e02c1471580980c7f4429be44b5'

// PR branch
def jmerepo='com.github.riccardobl.jmonkeyengine'
def jmeversion='211pr-SNAPSHOT'


// def jmerepo="org.jmonkeyengine"
// def jmeversion="3.3.0-211pr-SNAPSHOT"



repositories {
    maven { url 'https://jitpack.io' }   
    mavenCentral(); 
}


dependencies {
    testCompile jmerepo + ':jme3-core:' + jmeversion
    testCompile jmerepo + ':jme3-desktop:' + jmeversion
    testCompile jmerepo + ':jme3-lwjgl:' + jmeversion
    testCompile 'junit:junit:4.11'
}
```

### CODE REVIEW

**Comment by stephengold** [comment]
Please add tests to the jme3-core/src/test/com/jme3/scene package.

**Comment by Ali-RS** [comment]
@stephengold  I add the test in #1017 . 
Can this PR be merged ?

**Comment by empirephoenix** [comment]
Yes, I think so, thanks for the work

**Comment by riccardobl** [comment]
Thanks @Ali-RS  and sorry, i didn't have time to do it right away and then i forgot :persevere:

**Comment by stephengold** [comment]
I was waiting on @Ali-RS to commit some tests to the repo, as I requested in November.

**Pull request merged**
