### PR TITLE
Updated CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Ali-RS**
Added "Customs around integration, branching, tagging, and releases" section to contribution guide.

### CODE REVIEW

**Comment by stephengold** [comment]
I'm in favor of integrating this addition!

Though perhaps we should clarify that the admonition to squash PRs is directed at integrators, not submitters.

**Comment by Ali-RS** [comment]
You mean something like this: 

> Integrators should note, unless the history of the pull request is important, it should be integrated to a single commit using “squash and merge”. If the history is important, favor “rebase and merge”.
> Don’t create a merge commit unless GitHub cannot rebase the PR.

**Comment by stephengold** [comment]
Yeah, like that. Thanks.

**Comment by Ali-RS** [comment]
Done.

**Pull request merged**
