### PR TITLE
recursively detects improperly modified spatials

### PR DESCRIPTION
**Pull request by AquariusPower**
It will look for all improperly modified spatials and show enough information to let the developer more precisely identify the problem from [here](https://hub.jmonkeyengine.org/t/a-more-precise-exception-report-about-modifying-the-scene-from-another-thread/34982).

Obs.: the second/newest commit is a proposal clarification method naming deprecation (so nothing will break) basically in favor of:
/* use only for debug purposes */
Spatial.getDebugName()

### CODE REVIEW

**Comment by pspeed42** [comment]
Seems like if we just exposed the modified flags then all of this could be done with one external utility class and a user parameter (for the, to me, unnecessary 'debug name')... and it wouldn't clutter up the code with a check that most experienced JME users avoid naturally.

I mean, I'll leave it to the others but I'm against this patch.

**Comment by AquariusPower** [comment]
@pspeed42 both alternative suggestions are interesting (despite I still didnt find info about how it could be a 'user parameter'). Oh, these changes are solely intented towards new-comers.

**Comment by pspeed42** [comment]
re: (despite I still didnt find info about how it could be a 'user parameter')

spatial.setUserData("myDebugName", "This is a debug string")

re "Oh, these changes are solely intented towards new-comers."

Yes, but new-comers will learn their lesson fast and then understand more why it's an issue... but these changes will dirty up the code and increase the maintenance burden (without actually teaching those users what's really wrong).  We would have to support these calls basically forever even if next version we came up with a better way to do updates where this wasn't an issue anymore.

This kind of debugging stuff should not be embedded right into the core classes.

**Comment by AquariusPower** [comment]
You made me think about creating a JME debug class specialized in tracking problems we end users could create. It would never be a dependency to let things run. It could unsafelly access everything (even private), mainly whenever an uncaught exception happens, and would not even require the "modified flags" to be exposed.

But the Spatial.name is just for debug reasons as I learned, therefore it's method name is still confusing. Despite we should not use getName() as a coding base, if we do it, it will still work, but may break things by not reaching Spatials thru the expected way (ex. thru Lemur methods). I guess that will remain in the learning curve then... 

Good to know you are keeping it clear/simple to not clutter and create maintenance troubles.

I agree with you, I will just close it, thx!

**Pull request closed without merging**
