### PR TITLE
i18n

### PR DESCRIPTION
**Pull request by lifeinwild**
The current jmonkey source code can not be built in some countries. i fixed it.

### CODE REVIEW

**Comment by grizeldi** [comment]
You'd probably want to get rid of those "revert/merge/etc." commits from the PR.

**Comment by riccardobl** [comment]
Shouldn't squash-merge take care of that automatically?

**Comment by lifeinwild** [comment]
I succeeded in clean build in the last commit.

**Comment by riccardobl** [comment]
Thanks, merged. :+1:

**Pull request merged**
