### PR TITLE
Updated version.

### PR DESCRIPTION
**Pull request by mitm001**

### CODE REVIEW

**Comment by stephengold** [comment]
While a stable version 3.2 of the Engine is available, it's not (by itself) a "complete game development suite". That phrase refers to the SDK, not the Engine.

I think this change should wait until there's a stable version 3.2 of the SDK.

**Comment by mitm001** [comment]
Actually, the SDK mention shouldn't be there. Its mentioned in the next paragraph.

**Comment by mitm001** [comment]
Go to https://github.com/jMonkeyEngine/sdk/releases to download the jMonkeyEngine SDK. Read the wiki for a complete install guide. Power up with some SDK Plugins and AssetPacks and you are off to the races. At this point you're gonna want to join the forum so our tribe can grow stronger.

Should read,

Go to https://github.com/jMonkeyEngine/sdk/releases to download the jMonkeyEngine SDK. Read the wiki for a complete install guide. At this point you're gonna want to join the forum so our tribe can grow stronger.

Since the plugins and assetpacks are nonexistent and likely to never be fixed.

I can fix that also if you want.

**Comment by stephengold** [comment]
There are plenty of NetBeans plugins available. Good point about asset packs, however.

**Comment by Nehon** [comment]
So, do you guys agree on this, is it ok to merge?

**Comment by stephengold** [comment]
I think this change should wait until there's a stable version 3.2 of the SDK.

**Comment by grizeldi** [comment]
It's out now.

**Comment by Nehon** [comment]
true

**Pull request merged**
