### PR TITLE
address issue #1430: remove the jme3tools.navigation package

### PR DESCRIPTION
**Pull request by stephengold**
The deleted files have been moved to https://github.com/jMonkeyEngine-Contributions/jme3tools.navigation

### CODE REVIEW

**Comment by tlf30** [comment]
Looks good to me @stephengold

**Review by benjamij — APPROVED** [review]
Been years since I looked at this. But lgtm.

**Comment by stephengold** [comment]
> Been years since I looked at this. But lgtm.

It's nice to you know you're still around.

**Comment by benjamij** [comment]
haha likewise!

**Pull request merged**
