### PR TITLE
LwjglWindow:assign new thread to `mainThread` field.

### LINKED ISSUE #1721: SimpleApplication.stop(true) freezes the application
A call to `SimpleApplication.stop(boolean waitFor)` with `waitFor=true` on jME 3.5.0-beta4 with LWJGL3 causes the application to freeze. 

Hub reference: https://hub.jmonkeyengine.org/t/v3-5-0-beta-testing/45209/4

### PR DESCRIPTION
**Pull request by Ali-RS**
Fix #1721

### CODE REVIEW

**Comment by Ali-RS** [comment]
Will be merged in 24H.

**Comment by stephengold** [comment]
Thjank you for your contribution to our project. I think this fix is important enough to justify a "beta2" release!

**Comment by Ali-RS** [comment]
Yep. I already wanted to propose a beta 2 release after we merged this.

**Comment by stephengold** [comment]
I just realized it will actually be "3.5.0-beta5." Sorry for any confusion!

**Pull request merged**
