### PR TITLE
added a possibility to handle shaders errors.

### PR DESCRIPTION
**Pull request by JavaSaBr**
Added a possibility to handle shaders errors.
I use this to handle incorrect shaders during shader editing in my Editor:
https://bitbucket.org/JavaSabr/jme3-spaceshift-editor/commits/d4128e6b06e0ae2ce16d845ada8fa7215819b6e7

### CODE REVIEW

**Comment by empirephoenix** [comment]
Can you please reissue the pull request?  travis had some trouble yesterday, hopefully it will work today.

**Comment by Nehon** [comment]
This is totally unneeded.
You just have to catch renderException and parser the exception message.
I'm against this change

**Comment by JavaSaBr** [comment]
@Nehon Hi, so how can I fix a geometry which has an incorrect material in your case?

**Comment by Nehon** [comment]
the geometry doesn't need fixing, the material does.
see this https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/java/com/jme3/util/MaterialDebugAppState.java

**Comment by JavaSaBr** [comment]
@Nehon , wow, so I can use the:
`renderManager.preloadScene(dummyGeom);`
to validate a material, right? cool if it's true :+1:

**Pull request closed without merging**
