### PR TITLE
Set the minimum required OpenGL profiles for the geometry and tessellation shader test cases

### PR DESCRIPTION
**Pull request by rvandoosselaer**
See #1357

### CODE REVIEW

**Comment by rvandoosselaer** [comment]
I went through the rest of the examples, and did not encounter any other test scenerio's that required a higher core profile.

You can close the PR.

**Comment by stephengold** [comment]
Integrated into master branch at 3fa85bc and into v3.3 branch at 4b62b70 .

**Comment by stephengold** [comment]
Thank you, @rvandoosselaer !

**Comment by stephengold** [comment]
A couple caveats that just occurred to me:
 1. Setting the profile in the `main()` method doesn't help when tests are run from the test chooser, since the test chooser bypasses `main()`.
 2. Most of jme3-examples apps do not initialize the `AppSettings` or set the app title. In that case, the settings are saved from run to run, even between different apps. Unless you `setRenderer()` back to the default between runs, your testing may have missed cases where the default value is too low.

**Comment by rvandoosselaer** [comment]
I didn't consider your first remark. That is indeed correct. I haven't checked how the TestChooser is launching the examples. You will have different behaviour when launching.

The second caveat is something I already bumped into a lot of times, given the strict behaviour of Macs. I did make sure to reset my preferences after running those 2 shader tests before testing other examples.
I'm making a habit of using `AppSettings settings = new AppSettings(true);` whenever I write a new (test) application, to make sure I always use the default settings. When I want to deviate from them, I need to explicitly set it. I think it would be good practice to do this for all the examples.

**Comment by stephengold** [comment]
Regarding #2, I propose giving every example that modifies `appSettings` a title, so that it won't share the settings with the other examples.

**Comment by stephengold** [comment]
My proposal doesn't work, so `AppSettings(true)` seems to be the best solution.

**Comment by rvandoosselaer** [comment]
I’ll make it my ‘lockdown-project’ to systematically adapt all the test cases and force the default AppSettings.

I’ll first need to check how the TestChooser works so the settings are also applied when launching an application from the TestChooser.

**Comment by stephengold** [comment]
I think you'll need to modify TestChooser. Other than that, I don't foresee any difficulties.

**Pull request merged**
