### PR TITLE
AnimComposer: return AnimLayer on the makeLayer and removeLayer methods.

### PR DESCRIPTION
**Pull request by capdevon**
Standardize the `AnimComposer.makeLayer()` and `AnimComposer.removeLayer()` methods similar to `AnimComposer.makeAction()` and `AnimComposer.removeAction()` to simplify interaction with created and deleted objects.

### CODE REVIEW

**Comment by capdevon** [comment]
Are there any updates on this proposal? Has anyone had a chance to review it?

**Review by codex128 — APPROVED** [review]
These changes look fine to me.

**Review by neph1 — APPROVED** [review]
I'd take the opportunity to rename "l" "layer", but the method is so short it doesn't really matter.

**Comment by stephengold** [comment]
I used GitHub's web editor to resolve the merge conflict.

**Comment by stephengold** [comment]
That broke the build. Hang on while I fix it...

**Comment by stephengold** [comment]
All set. Thanks for this contribution, @capdevon !

**Pull request merged**
