### PR TITLE
Nifty batch fix - memory improvement

### PR DESCRIPTION
**Pull request by joliver82**
Issue found at jme3-nifty code that depending on the batch configuration will lead to gui rendering issues.

More information in the forum thread: https://hub.jmonkeyengine.org/t/potential-issue-in-nifty-batch-rendering/42515

### CODE REVIEW

**Comment by stephengold** [comment]
@joliver82 please provide a compact test that demonstrates the issue, preferably in the `jme3test.niftygui` package of the `jme3-examples` sub-project.

**Comment by joliver82** [comment]
@stephengold sure but, could you be more specific on what kind of test do you want?

**Comment by stephengold** [comment]
An application that uses the batched renderer with multiple atlases and `disposeImagesBetweenScreens=true`.

**Comment by joliver82** [comment]
OK, I'll update the branch with the test once done ;)

**Comment by stephengold** [comment]
I'm going to try the test. Unless I find some new concern, I'll integrate this PR.

**Comment by stephengold** [comment]
I tried the test, but its behavior seemed identical with or without the fix. I see that the testcase is incomplete, so I've decided to postpone integration.

**Comment by joliver82** [comment]
The test is not finished still, I need to add more images so it really uses multiple atlases and breaks without the fix

**Comment by stephengold** [comment]
Progress?

**Comment by joliver82** [comment]
Not at all, I just upgraded this branch with master, to continue working on it having latest code and avoiding any potential future conflict

**Comment by joliver82** [comment]
> Progress?

Hi @stephengold as written in the related forum thread, there was not issue because of how the atlas is overwritten but I'm taking advantage of this PR to improve memory usage in nifty batch rendering

**Comment by MeFisto94** [comment]
So this PR would be "ready" for integration? (minus the merge conflict)

**Comment by joliver82** [comment]
> So this PR would be "ready" for integration? (minus the merge conflict)

From my point of view, it is.

**Pull request merged**
