### PR TITLE
fixed two problems with asset manager:

### PR DESCRIPTION
**Pull request by JavaSaBr**
1. can't load classes from asset class loaders.
2. can't load resources from asset class loaders.

### CODE REVIEW

**Comment by JavaSaBr** [comment]
@empirephoenix @Nehon could you review this PR, please?

**Comment by Nehon** [comment]
I don't get what this fixes, could you please explain the issue a bit more?

**Comment by JavaSaBr** [comment]
@Nehon for example, I have a j3o model which includes materials with shaders and controls which don't exist in the main class loader, so when I try to load it, I have class not found exceptions and asset not found exceptions, because the process of loading assets from classpath doesn't look at additional class loaders of asset manager. The same issue with loading controls. 
Is it clear? :)

**Comment by Nehon** [comment]
Ok I get it now... that actually looks like a bug...

**Comment by JavaSaBr** [comment]
@Nehon thanks :)

**Comment by Nehon** [comment]
Not merging it for now, waiting for others to review. If it's not merged in a couple of days, please ping me.

**Comment by JavaSaBr** [comment]
@Nehon ok

**Comment by empirephoenix** [comment]
} catch (InstantiationException e) {
                  } catch (IllegalAccessException e) {		                  } catch (IllegalAccessException e) {
                  }		                  }

What about this? as this would hide problems with initializers. I totally understand the need to do the continue for the not found case, but if a class could be loaded, why ignore errors on init?
Else than this I think this change makes sense.

**Comment by JavaSaBr** [comment]
@empirephoenix I just wanted to make minimal changes, I didn't look at the code block :)

**Comment by Nehon** [comment]
Seems that the code was already doing that... It's weird, that those exception are not re thrown...
IMO they were supposed to be thrown at first and has been silenced later for more proof loading....

**Comment by JavaSaBr** [comment]
@Nehon I think changes of this code block should be in a separated PR ;)

**Comment by Nehon** [comment]
Agree

**Comment by empirephoenix** [comment]
Well fi that was the prior behaviour, I see no reason against this.

**Pull request merged**
