### PR TITLE
Added getter and setter for LegacyApplication's speed

### PR DESCRIPTION
**Pull request by 8Keep**
#978

### CODE REVIEW

**Comment by pspeed42** [comment]
I don't think this is a good change as it makes something public through the API that should not be public... and in apps that want it to be public it is trivial for them to add.  (Plus, I'm kind of against the 'speed' idea anyway, my own last name not withstanding.)

**Comment by pspeed42** [comment]
...not only that, speed = 0 seems to be the only interesting value in LegacyApplication and SimpleApplication does its own speed processing anyway.  I think the idea of speed should be completely removed from LegacyApplication.

**Comment by 8Keep** [comment]
I'm available to do whatever should be done. I guess we wait for Stephens response.

**Comment by stephengold** [comment]
Let's discuss at issue #978.

**Comment by stephengold** [comment]
8Keep, I took at look at your pull request, and it's perfect. Pspeed and I just need to agree on whether issue #978 was a good idea or not.

**Comment by 8Keep** [comment]
No problem! If you come across any more menial fixes with no time to make a pull request, I'd love to take them to get more practice.

**Comment by stephengold** [comment]
Would you be willing to rework your PR to meet the new requirements (SimpleApplication instead of LegacyApplication)?

**Comment by 8Keep** [comment]
Yes

**Comment by 8Keep** [comment]
Let me know if this is acceptable.

**Comment by stephengold** [comment]
Hm. I don't think we should move the `speed` variable from `LegacyApplication` just yet. Some users may be depending on it. Would you mind putting it back in?

**Comment by stephengold** [comment]
There's still one change in `LegacyApplication` that needs to be reverted.

**Comment by 8Keep** [comment]
Lots of commits for very little. Should I create a new PR with just the end changes?

**Comment by stephengold** [comment]
No need for a new PR. GitHub has a "Squash and merge" option which I will now employ...

**Pull request merged**
