### PR TITLE
Android buffer allocator implementation

### PR DESCRIPTION
**Pull request by joliver82**
A new buffer allocator created to solve ReflectionAllocator exceptions while freeing memory (destroyDirectBuffer method) caused by new buffer wrapper classes (java.nio.ByteBufferAs[type]Buffer) in android and improving memory management not having to wait for GC to free direct memory if desired.

Related forum post: https://hub.jmonkeyengine.org/t/exception-when-destroying-direct-memory-in-android/42483

### CODE REVIEW

**Comment by Ali-RS** [comment]
Thanks :)

**Comment by Ali-RS** [comment]
Merginh PR #1147 which changes OGLESContext.java (https://github.com/jMonkeyEngine/jmonkeyengine/pull/1147/files#diff-51f8ab703009d20f32b7588036e3fb27) I was expecting GitHub show conflicts with base branch for this PR but seems it is Ok.
So just to get sure does this PR need to be updated with jme's master branch?

**Comment by joliver82** [comment]
Changes to OGLESContext in this PR are between lines 62 and 84 which were not modified by the gl3 PR, so there's no conflict and can be merged safely. But if you feel more comfortable updating this branch to master previously to merge tell me and I'll do ;)

**Comment by Ali-RS** [comment]
Okay, now that it is safe, then I guess no need to update. 
Thanks for the clarification :)

**Pull request merged**
