### PR TITLE
fix issue 1672 (inefficient logging in Node.java)

### PR DESCRIPTION
**Pull request by vxel**
This fixes issue #1672

### CODE REVIEW

**Comment by stephengold** [comment]
Looks good to me! Unless there's substantial review, I will integrated this in about 24 hours.

**Comment by pspeed42** [comment]
I kind of wish we'd just changed the "this.toString()" into just "this" instead.  That's a garbage anti-idiom that would have prevented the whole issue if done properly in the first place.

**Comment by stephengold** [comment]
I like pspeed's solution better than adding guard code. @vxel would you be willing to implement that solution instead?

**Comment by vxel** [comment]
Agree with that too. PR updated.

PS: sorry for the force-push I merged wrong commits...

**Comment by stephengold** [comment]
Force pushes are okay in this case because "fix/1672" is your own private branch. But unnecessary because I'm going to squash the history when I integrate this PR.

**Comment by stephengold** [comment]
Thanks for your contribution, @vxel !

**Pull request merged**
