### PR TITLE
Migrate TestSkeletonControlRefresh to new anim sys

### PR DESCRIPTION
**Pull request by syluna**
Migrate TestSkeletonControlRefresh to new Anim system

### CODE REVIEW

**Comment by stephengold** [comment]
It looks like there were transient errors during some of the checks. @syluna Can you re-run the jobs yourself, or do you need assistance?

**Comment by syluna** [comment]
I think it's just because I am stupid (Using my 1.8 jdk and write expression for loop)

**Comment by stephengold** [comment]
Perhaps special permissions are required. I'm unsure. I restarted the checks for you.

**Comment by syluna** [comment]
Ok thanks (I'm noob I don't know how to do this)

**Comment by stephengold** [comment]
I'm not sure what's causing those checks to fail, but I believe the failures are unrelated to your changes.

**Comment by syluna** [comment]
I agree, the changes are local to the test and run on my linux and windows system like a charm (I dont have mac :s).

**Comment by stephengold** [comment]
Why did you close this?

**Pull request closed without merging**
