### PR TITLE
Make 'Q' and 'Z' move flyCam along its up vector

### PR DESCRIPTION
**Pull request by g-rocket**
In FlyByCamera, rather than hardcoding them to be along the Y axis, 'Q' and 'Z' now move with and against respectively whatever direction has been set as its up vector (using setUpVector).

### CODE REVIEW

**Comment by afonsolage** [comment]
And this will break all existing flyCam. At least add a boolean to enable or disable it. In my project, I use flyCam as it is and this change will lead me to reverse it on custom code.

**Comment by DannyJo** [comment]
I think this sounds like a bug fix to be honest and it shouldn't break code unless you've set the initial up vector to something other than Y and then use Q and Z to move along the Y axis anyway which to be honest sounds a bit odd to be doing. I'm guessing @g-rocket actually uses a different up vector for the fly cam and that's why this has come about.

This pull request has my vote unless a core dev can spot an error in that one line of code that has changed.

**Comment by empirephoenix** [comment]
I think @afonsolage miinterpreted your comment, as using the up vector of the current view direction. Which would change behaviour.

**Comment by shadowislord** [comment]
This is a behavior change, yes. I am not sure if its significant enough to warrant avoiding fixing this, since it is not expected that it would always use Y when you change the up vector.

**Comment by pspeed42** [comment]
Though if we are going to add bloat to a class that shouldn't be used in real games... why not have made it a boolean flag to turn on/off?

**Comment by empirephoenix** [comment]
not relevant/class not intended for productive use

**Pull request closed without merging**
