### PR TITLE
JmeSurfaceView: Package migration

### PR DESCRIPTION
**Pull request by Scrappers-glitch**
This PR includes : 
- Migration to new `com.jme3.view.surfaceview` package.
- Addition of `package-info.java` for the new packages.
- Update of jme3-copyright.

This PR targets : 
- issue #1803.
- Parts of issue #1800.

### CODE REVIEW

**Comment by Scrappers-glitch** [comment]
Let me know if there any required changes for this PR.

**Comment by Scrappers-glitch** [comment]
I need to know what is next to get this merged, please let me know.

**Comment by stephengold** [comment]
I plan to merge this after PR 1748 is integrated.

**Comment by Scrappers-glitch** [comment]
> I plan to merge this after PR 1748 is integrated.

Thanks for looking into this.

If you would like, i can prepare a simple quick migration guide for these changes to be included in the new release.

**Comment by stephengold** [comment]
Thanks for your contribution. I'm unsure when/if there will be a new release.

The changes seem very straightforward; I don't think a migration guide will be needed.

**Comment by Scrappers-glitch** [comment]
> Thanks for your contribution. I'm unsure when/if there will be a new release.
> 
> The changes seem very straightforward; I don't think a migration guide will be needed.

Yeah, anyway, if you changed plans and urgently needs it, just ping me here.

**Pull request merged**
