### PR TITLE
Added support of overriding

### PR DESCRIPTION
**Pull request by JavaSaBr**
Added support of overriding for class EnvironmentCamera

### CODE REVIEW

**Comment by Nehon** [comment]
There is a lot of noise in this change because I guess of your formatting scheme.
Several questions : 
Why do you need to override this class? What feature do you miss?
Why the early returns instead of the more classic "if"

**Comment by JavaSaBr** [comment]
> Why do you need to override this class? What feature do you miss?
For my case:
```
@Override
    protected Camera createOffCamera(final int mapSize, final Vector3f worldPos, final Vector3f axisX, final Vector3f axisY, final Vector3f axisZ) {
        final Camera offCamera = super.createOffCamera(mapSize, worldPos, axisX, axisY, axisZ);
        offCamera.setFrustumPerspective(90f, 1f, 1, GraphicUtils.SKY_SPHERE_RADIUS);
        return offCamera;
    }
```

> Why the early returns instead of the more classic "if"
Anti practice for:
```
if(cond) {
			if(cond) {
				if (cond) {
					if (cond) {
						
					}
				}
			}
		}
```

**Comment by Nehon** [comment]
1. createOffCamera is already protected. You can do that without the change. If you need any attribute from the class I'd rather create accessors than making them protected.
2. Not relevant in this case, there is only one condition... your change doesn't make it more readable...

**Comment by JavaSaBr** [comment]
1. protected FINAL...

**Comment by Nehon** [comment]
OH! duh. You should have started with that.
Ok I'll push a change in this regard.

**Comment by pspeed42** [comment]
Early returns are a billions times more readable.  It's funny because people who are against early returns seem to have no problem with using "break" in a loop and it's exactly the same thing.  In C, there was a point to this structured dogma but in any language with a finally {} clause there is no point.

**Comment by gouessej** [comment]
@pspeed42 It's a matter of taste but I like neither early returns nor break (I prefer picking a right loop condition) & continue. Using early returns can enhance the readability but abusing of returns in the whole body of a method drives it harder to understand (in my humble opinion). If you have only small methods, having several points of exit isn't a source of trouble but it's not the case if you have large methods.

I find structured programming helpful to make the proof of a program, not only with languages with no RAII (Resource Acquisition Is Initialization).

**Pull request merged**
