### PR TITLE
Fixed the example TestMultiRenderTarget

### PR DESCRIPTION
**Pull request by JohnLKkk**
This case originally seemed to be written by a retired predecessor to test delayed rendering, but its content is missing. I rewritten this case to help newbies use MRT technology outside of jme.

### CODE REVIEW

**Comment by stephengold** [comment]
Thanks for your contribution to JMonkeyEngine.

**Comment by stephengold** [comment]
Please add back the "@Override" annotations you removed from the java source.

It's confusing to have 2 variable named "mrtLightingMaterial".  Please rename one of them.

I don't understand what the comments at the end of `reshape()` are for. I realize you didn't add them. Are they still relevant?

The `setDepthTexture()` is deprecated. Please use the new `setDepthTarget()` method instead.

**Comment by JohnLKkk** [comment]
> Please add back the "Override" annotations you removed from the java source.
> 
> It's confusing to have 2 variables named "mrtLightingMaterial". Please rename one of them.
> 
> I don't understand what the comments at the end of `reshape()` are for. I realize you didn't add them. Are they still relevant?
> 
> The `setDepthTexture()` method is deprecated. Please use the new `setDepthTarget()` method instead.

Okay, I have been busy adjusting the RenderPipeline recently, and I only noticed your reply today. Feel sorry...

**Comment by lm165678** [comment]
The comments at the end of the reshape() method are some optimization techniques to help novices to implement MRT-based DeferredRender. To make the case as simple as possible, I have deleted these comments (these are actually the comments left by the previous predecessor)

**Comment by JohnLKkk** [comment]
The comments at the end of the reshape() method are some optimization techniques to help novices to implement MRT-based DeferredRender. To make the case as simple as possible, I have deleted these comments (these are actually the comments left by the previous predecessor)

**Comment by JohnLKkk** [comment]
https://github.com/jMonkeyEngine/jmonkeyengine/pull/1654

**Comment by stephengold** [comment]
Why did you create PR #1654? I imagine it would be easier to push additional commits to this PR...

**Comment by JohnLKkk** [comment]
This PR was modified directly on the master, and the other PR was modified on my own branch'kkk'.

**Comment by stephengold** [comment]
Shall I close this one and review 1654?

**Comment by JohnLKkk** [comment]
Yes, trouble you. thanks

**Pull request closed without merging**
