### PR TITLE
Changed access to some methods of shadow render.

### PR DESCRIPTION
**Pull request by JavaSaBr**
Changed access to some methods of shadow render. I'm going to use it for my editable versions of shadow renders classes.

### CODE REVIEW

**Comment by Nehon** [comment]
mhh.... you gonna have to explain more than that.... why do you need access to those methods?

**Comment by JavaSaBr** [comment]
I want to add supporting cloneable to ShadowRenderer:
https://bitbucket.org/JavaSabr/jme3-spaceshift-editor/src/2ed5cf7c318237e34d15dd8ca63bf7ded9bbbdc2/jme3-spaceshift-extension/src/com/ss/extension/scene/renderer/EditableDirectionalLightShadowRenderer.java?at=0.9.2&fileviewer=file-view-default
also, I want to have a possibility to save/load shadow filters:
https://bitbucket.org/JavaSabr/jme3-spaceshift-editor/src/2ed5cf7c318237e34d15dd8ca63bf7ded9bbbdc2/jme3-spaceshift-extension/src/com/ss/extension/scene/filter/impl/EditableDirectionalLightShadowFilter.java?at=0.9.2&fileviewer=file-view-default

Now I use reflection API to get access to it :(

**Comment by Nehon** [comment]
"I want to add supporting cloneable to ShadowRenderer:"
ok... so why don't you PR this.
Make the ShadowRenderer implement Cloneable and Savable and that will be ok.

**Comment by JavaSaBr** [comment]
Ok, I will try to add it to core classes ;)

**Pull request closed without merging**
