### PR TITLE
Bump LWJGL3 version to '3.2.3'

### PR DESCRIPTION
**Pull request by Ali-RS**
I tested on a bunch of examples from jme3-examples and works fine for me. 
Tested on Linux.

### CODE REVIEW

**Comment by grizeldi** [comment]
I did this locally and stuff seemed to work fine. Also on linux.

**Comment by grizeldi** [comment]
Also, while you're at it, can you bump up the version in jme3-vr as well?

**Comment by Ali-RS** [comment]
Yep, done.

**Comment by stephengold** [comment]
1. Did anyone test on a Macintosh? On Windows? On Android?
2. Did testers confirm that the correct LWJGL version was printed on the `INFO` line during startup?
3. Did anyone test both fullscreen and windowed modes?
4. Was `TestNiftyExamples` run? Did the audio work?
5. Was `TestResizableApp` run?

**Comment by Ali-RS** [comment]
Tested on Linux:

> Did testers confirm that the correct LWJGL version was printed on the INFO line during startup?

Yes

> Did anyone test both fullscreen and windowed modes?

Yes

> Was TestNiftyExamples run? Did the audio work?

It runs and audio works. (btw, not lwjgl related issues but I observed Textfield and Drop down list examples throw exeption. As they are not related to this post I will make a new issue for it)

> Was TestResizableApp run?

It runs and I can resize window but I observed an odd behavior when resizing. 
Screenshot_2019-09-20_10-05-45

It happens on both LWJGL 3.2.1 and 3.2.3 but works fine on LWJGL2.

**Comment by stephengold** [comment]
I'll test on Windows...

**Comment by stephengold** [comment]
On Windows, `TestResizableApp` crashes during startup:
```
Sep 20, 2019 9:56:49 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.3-Ali-RS-patch-1-6919
 * Branch: Ali-RS-patch-1
 * Git Hash: d3f8621
 * Build Date: 2019-09-20
Sep 20, 2019 9:56:50 AM com.jme3.app.LegacyApplication handleError
SEVERE: Failed to create display
java.lang.NullPointerException
	at jme3test.app.TestResizableApp.reshape(TestResizableApp.java:63)
	at com.jme3.system.lwjgl.LwjglWindow$2.invoke(LwjglWindow.java:258)
	at org.lwjgl.glfw.GLFWWindowSizeCallbackI.callback(GLFWWindowSizeCallbackI.java:35)
	at org.lwjgl.system.JNI.invokePV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwShowWindow(GLFW.java:2527)
	at com.jme3.system.lwjgl.LwjglWindow.showWindow(LwjglWindow.java:301)
	at com.jme3.system.lwjgl.LwjglWindow.createContext(LwjglWindow.java:295)
	at com.jme3.system.lwjgl.LwjglWindow.initInThread(LwjglWindow.java:453)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:578)
	at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:427)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:463)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:424)
	at com.jme3.app.SimpleApplication.start(SimpleApplication.java:125)
	at jme3test.app.TestResizableApp.main(TestResizableApp.java:56)

Sep 20, 2019 9:56:50 AM com.jme3.system.lwjgl.LwjglWindow run
SEVERE: Display initialization failed. Cannot continue.
```

**Comment by stephengold** [comment]
JME 3.2.4 crashes in a similar fashion, so at least it's not a regression. I'll open an issue for it.

**Comment by stephengold** [comment]
Testing with PR uncovered issues #1191 and #1192, neither of which is related to the PR.

**Comment by stephengold** [comment]
Also #1193.

We need to keep filing and investigating LWJGL3 issues. And since LWJGL 3.2.3 doesn't seem to behave much different from 3.2.1, we may as well use 3.2.3 .

**Pull request merged**
