### PR TITLE
DynamicAnimControl

### PR DESCRIPTION
**Pull request by stephengold**
(1) publicize `Joint.applyBindPose()` because `DynamicAnimControl` needs to know the bind pose
(2) add `DynamicAnimControl` and related classes in the `com.jme3.bullet.animation` package
(3) revise the `TestBoneRagdoll` and `TestRagdollCharacter` apps to use `DynamicAnimControl` instead of `KinematicRagdollControl`
(4) remove the `TestIK` app which was never completed and had an unhealthy dependency on `TestBoneRagdoll`

### CODE REVIEW

**Comment by quazi-irfan** [comment]
Are you planning to write an wiki page on `DynamicAnimControl`?

**Comment by stephengold** [comment]
I already started a tutorial at Minie:
   https://github.com/stephengold/Minie/blob/master/README.md#dac
It needs clarification and expansion. Most of it was written while I was supporting oxplay2, my alpha tester. Each time they had difficulty or asked an interesting question, I added the solution or the answer to the tutorial.

The `jme3-bullet` version of `DynamicAnimControl` is less elaborate. It wants some simpler documentation. I will draft some wiki documentation, but it would help me to have alpha testers, people using the software, asking questions, and giving feedback. Would you like to be a tester?

**Comment by quazi-irfan** [comment]
I'd love to be a tester.

**Comment by stephengold** [comment]
Can I assume you want to use `DynamicAnimControl` for ragdoll animation, or do you have some other application in mind?

**Pull request merged**
