### PR TITLE
Attempt to fixing 1074

### PR DESCRIPTION
**Pull request by karanehra**
This is my first attempt at resolving #1074.

Added getters for "alphaToCoverage" and "defaultAnisotropicFilter" in the Renderer interface.
Added respective method stubs to GLRenderer and NullRenderer implementing Renderer.

I'm still trying to implement the exact method in the GLRenderer. Any help appreciated.

### CODE REVIEW

**Comment by stephengold** [comment]
Needs tests to show that the new methods work as intended.

**Comment by riccardobl** [comment]
The indentations is very wrong, besides that this seems ok.

**Comment by stephengold** [comment]
Some of the changes are unnecessary. Please revert the changes to `jme3-core/build.gradle` and `TestAspectRatio.java`.

The files in `jme3-core/.idea` appear to be IDE-specific and should not be part of this pull request. Please remove them. To avoid committing such files in the future you may want to add `**/.idea` to your `.gitignore` file.

As Riccardo pointed out, the added code in `GLRenderer.java` and `NullRenderer.java` isn't correctly indented. Please reformat this code, either to match the surrounding code or else to conform to the [Google style](https://google.github.io/styleguide/javaguide.html#s4-formatting).

**Comment by karanehra** [comment]
Added the requisite changes.

**Comment by stephengold** [comment]
A few more requests...

1. `TestAlphaToCoverage.java` should also verify the behavior of `getAlphaToCoverage()` *before* `Caps.Multisample` is added: verify that it returns `false`.
 
2. Since `TestAlphaToCoverage.java` doesn't display anything relevant, I suggest adding a `stop()` at the end of `simpleInitApp()` to terminate the test.

3. The purpose and expected result of `TestAlphaToCoverage.java` should be documented. Please add a Javadoc comment similar to the one in `TestAspectRatio.java`.

**Comment by karanehra** [comment]
Done sir.

**Comment by riccardobl** [comment]
TBH this test seems unnecessary, but if we really want to keep it, i think it should go in tests (not in examples). Actually is it possible to make it an unit test?

**Comment by karanehra** [comment]
I actually tried that using the help of @stephengold . But we were having a lot of problems going that way.

**Comment by louhy** [comment]
Care to share which problems? Maybe there isn't a better option, but maybe someone can think of a workaround - we're here to help! :grin:

**Comment by karanehra** [comment]
Reverted all unnecessary changes. @riccardobl i mentioned you in the relevant thread. We would appreciate your help.

**Comment by karanehra** [comment]
@louhy what's your handle at hub.jmonkeyengine? I'll mention you too.

**Comment by louhy** [comment]
@karanehra Handle same as here - but I'll see it.

**Comment by riccardobl** [comment]
@karanehra which thread exactly?

**Comment by karanehra** [comment]
@riccardobl the relevant thread at hub.jmonkeyengine

**Comment by riccardobl** [comment]
I can't see any relevant thread and i didn't get any mention :man_shrugging:

**Comment by stephengold** [comment]
The thread is a private message thread between me and @karanehra:
   https://hub.jmonkeyengine.org/t/eager-to-contribute/41866/61

If it's not visible to @riccardobl and @louhy at this point, then I don't know how to make it visible.

@karanehra tried to make an automated test using `junit`: modified the `build.gradle` to add the necessary `testCompile` and `testRuntime` dependencies, explicitly loading the `lwjgl` native library, and instantiating a `GLRenderer`. However, we discovered that the renderer would need a `Display` in order to be properly initialized. At that point, I suggested writing a `SimpleApplication` instead.

**Comment by riccardobl** [comment]
I can't access it, i think you mentioned someone else lel.
I see, it might be possible to configure the CI to use software render, then you would have the display. But i think this is eventually something for the future.

**Comment by louhy** [comment]
Ahh, sounds like what they call "headless" mode. Seen it done in JavaFX land but not sure how easy (or possible) to do it for GL. Would be cool but probably a mini-project on its own.

**Pull request merged**
