### PR TITLE
Added removeAction(), removeLayer() and removeCurrentAction() to AnimComposer

### PR DESCRIPTION
**Pull request by Ali-RS**

### CODE REVIEW

**Comment by empirephoenix** [comment]
Can you explain what this does? I have no idea what it is supposed to solve/fix/improve :)

**Comment by Ali-RS** [comment]
It's an improvement for AnimComposer which is aimed for new animation system for JME 3.3. 
I believe it's not completed yet, and @Nehon is the one who works/was working on this system. 

```
    public void removeLayer(String name) {
        layers.remove(name);
    }
```
Having an option to makeLayer() you should also provide an option to remove it. Shouldn't it ? 
The same goes for removeAction(). 

   ```
  if (actionName == null) {
            // Clear current action from specified layer
            l.currentAction = null;
            return null;
        }
```
this one let you stop an specific layer from interpolation it's current action with out removing layer. Which is meant for : 
 
https://github.com/jMonkeyEngine/jmonkeyengine/blob/eeac6d10eb3a5a128dd7988775b35cd5a756681c/jme3-core/src/main/java/com/jme3/anim/AnimComposer.java#L162 

As @Nehon is not around so I guess I should ask @stephengold  and @pspeed42 to take a look at it.

**Comment by Ali-RS** [comment]
Added an appropriate javadoc for setCurrentAction() method.

**Comment by Ali-RS** [comment]
Moved removing of current action to a separate method.

**Comment by Ali-RS** [comment]
Can this be merged ?

**Comment by stephengold** [comment]
How about JavaDoc for the added methods `removeAction()`, `removeCurrentAction()`, and `removeLayer()`?

**Comment by Ali-RS** [comment]
@stephengold ,  JavaDoc added.

**Comment by Ali-RS** [comment]
@stephengold  thanks so much for merging the PR :)

**Pull request merged**
