### PR TITLE
downgrade or delete unnecessary library dependencies

### PR DESCRIPTION
**Pull request by stephengold**
These unnecessary dependencies were discovered with the aid of Intellij IDEA, which is an imperfect tool. So the changes will need careful review and testing.

### CODE REVIEW

**Comment by Joao839** [comment]
E

**Comment by stephengold** [comment]
> E

E? Please elaborate.

**Comment by stephengold** [comment]
I don't plan to include this in v3.5, because the valuable changes here (reducing app size at runtime) could also potentially break existing builds. The changes to "test" dependencies are very safe (because they get tested thoroughly by CI) but have correspondingly less benefit (since they don't affect apps).

**Comment by stephengold** [comment]
Unless there's substantial discussion, I plan to integrate this PR in about 24 hours.

**Pull request merged**
