### PR TITLE
fix for #1297

### PR DESCRIPTION
**Pull request by neph1**
This fixes https://github.com/jMonkeyEngine/jmonkeyengine/issues/1297 while retaining previous functionality. Verified using russian locale. Generates something like this:
2020-04-05 13:01:11.588 6397-6439/com.jarlure.paperdorm I/System.out: KeyCode=0,Charactors=р
2020-04-05 13:01:11.588 6397-6439/com.jarlure.paperdorm I/System.out: KeyChar=��

### CODE REVIEW

**Comment by stephengold** [comment]
This PR shouldn't be integrated as it presently stands because it unnecessarily modifies the entire file AndroidTouchInput.java

PRs should modify as few lines as possible.

**Comment by stephengold** [comment]
I see what happened. You removed the carriage-return (^M) from the end of each line. Probably your Git is misconfigured. Please add back the carriage returns and push that correction to this PR.

**Comment by stephengold** [comment]
Are you using CMake or ndk-build?

**Comment by neph1** [comment]
Perhaps I should know this, but how should git be configured? I've tried 
git config --global core.autocrlf input
git config --global core.autocrlf false
and also manually set line ending to LF. I've tried reverting the file and redo the changes, all with the same result.

**Comment by stephengold** [comment]
Back when I used MS Windows for development, I had `core.autocrlf=true`.

**Comment by neph1** [comment]
I am on linux. But the repo is very old, since my windows era. Perhaps it's related to that. I'll look into it again when I have time. I'll probably close this PR and create a new branch to make it look cleaner.

**Comment by stephengold** [comment]
Where's the new branch?

**Comment by ItsMike54** [comment]
Any update on this?

**Comment by 8Keep** [comment]
@neph1 I still see the line endings have changed 

It might be easier clone the repo fresh since it's gone through a transition from windows to linux, I have no idea what settings would need to be changed

**Comment by MeFisto94** [comment]
https://github.com/jMonkeyEngine/jmonkeyengine/pull/1323/files?diff=unified&w=1 is what github sees atm when trying to ignore whitespace changes

**Pull request merged**
