### PR TITLE
Fix issue #2056 . Check for NaN uniforms

### PR DESCRIPTION
**Pull request by riccardobl**

### CODE REVIEW

**Comment by pspeed42** [comment]
Note regarding the protected void isValidNumber(float v) methods.

...because they are protected it is harder for Java to inline them but even if asserts are turned off they will be called.

Either way, I wonder if it would be better if isValidNumber() simply returned true/false and then the calls are replaced with asserts... then when asserts are turned off no extra calls are made.

Else, isValidNumber() should be renamed because "is" implies a boolean return.

**Comment by pspeed42** [comment]
My understanding is that if assertions are disabled then the entire part after "assert" is removed... including the string concatenation.

**Comment by pspeed42** [comment]
...and by the way, I think this kind of instrumenting is really great for those "special times" when it's necessary.

**Comment by riccardobl** [comment]
I added the values to the assert messages

**Comment by riccardobl** [comment]
If there aren't objections i will merge this

**Comment by capdevon** [comment]
Hi Riccardo, please take a look at my revision before merging the code, there are formatting errors in the code and double semicolons at the end of the instructions.

**Comment by riccardobl** [comment]
> Hi @riccardobl, please take a look at my revision before merging the code, there are code formatting errors, extra lines and double semicolons at the end of the instructions. Could you please correct them?

Mhh i don't see your revision anywhere, but i think i've fixed the issues you pointed out, see the last commit

**Comment by Ali-RS** [comment]
Looks like he forgot to "submit" the reviews, so they won't be displayed to others. 
This also happened to me before!

**Comment by capdevon** [comment]
> Looks like he forgot to "submit" the reviews, so they won't be displayed to the public. This also happened to me before!

@Ali-RS Correct, I have submitted the revision which should now be visible. 
Thanks for your patience @riccardobl . I think there is still a little something to correct ;)

**Comment by riccardobl** [comment]
Done

**Pull request merged**
