### PR TITLE
Fix for XMLExporter issues in #2310

### PR DESCRIPTION
**Pull request by JosiahGoeman**
Includes fixes for all issues listed in https://github.com/jMonkeyEngine/jmonkeyengine/issues/2310 and refactors related classes for readability, adherence to style guide, and elimination of duplicate code.  Also adds unit tests for implementations of the OutputCapsule and InputCapsule interfaces.  Currently one [test is commented out](https://github.com/JosiahGoeman/jmonkeyengine/blob/fdaa7b7b1013e4158f6be8d0ceade7c36830aca6/jme3-plugins/src/test/java/com/jme3/export/InputOutputCapsuleTest.java#L641) because BinaryExporter fails it, see https://github.com/jMonkeyEngine/jmonkeyengine/issues/2312.

### CODE REVIEW

**Comment by JosiahGoeman** [comment]
Wait, why did GitHub include the commit from my previous pr?  It doesn't change any files anymore.  Does it just always do that if you don't make a separate branch for each issue?

**Comment by stephengold** [comment]
I'm unsure what happened. It might have something to do with creating a pull request in your "master" branch. Does the "files changed" tab look correct to you?

**Comment by JosiahGoeman** [comment]
Yes, the files changed are correct.

**Comment by JosiahGoeman** [comment]
Alright, I think this should be ready for review.

**Comment by stephengold** [comment]
If there's no substantive review or discussion, I'll run some simple tests of my own and then integrate this PR.

**Comment by stephengold** [comment]
My tests turned up an issue that's probably related to this change. I'll troubleshoot and post my findings here.

**Comment by stephengold** [comment]
The issue I'm seeing is an infinite recursion that occurs while writing a Minie `PhysicsVehicle` to an `XMLExporter`. However, I don't fully understand what's going wrong...

The test app looks like this:
```java
        NativeLibraryLoader.loadNativeLibrary("bulletjme", true);
        CollisionShape shape = new SphereCollisionShape(1f);
        PhysicsVehicle body = new PhysicsVehicle(shape, 1f);

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        XMLExporter exporter = new XMLExporter();
        try {
            exporter.save(body, outputStream);
        } catch (IOException exception) {
            throw new RuntimeException(exception);
        }
```

The infinite recursion is as follows:
`PhysicsVehicle.write()` line 846 invokes
`PhysicsRigidBody.write()`. At line 1442, that invokes
`DOMOutputCapsule.write()`. At line 406, that invokes
`RigidBodyMotionState.write()`. At line 366, that invokes 
`DOMOutputCapsule.write()`. And at line 406, that invokes
`PhysicsVehicle.write()` again.

There's only one `PhysicsVehicle` object in the test app, but it appears `DOMOutputCapsule` has forgotten it's already in the process of writing that `PhysicsVehicle`. The cycle repeats many times, until eventually the test app crashes with a `StackOverflowError`.

The same test app works fine if I replace `XMLExporter` with `BinaryExporter`.

**Comment by codex128** [comment]
I took a quick peek at it, and it looks like PhysicsVehicle contains a PhysicsRigidBody, which it attempts to save. The PhysicsRigidBody contains a RigidBodyMotionState, which it also attempts to save. Finally, the RigidBodyMotionState contains the original PhysicsVehicle, which it also attempts to save, and the process starts all over again.

I don't know why it only fails with XMLExporter, but I'd guess that BinaryExporter maybe has some sort of check for that sort of dependency issue.

**Comment by stephengold** [comment]
> I'd guess that BinaryExporter maybe has some sort of check for that sort of dependency issue.

The test succeeds with `XMLExporter` in v3.7.0-stable, which means there was *also* a check in `XMLExporter`, and this PR disabled that check. I'm hoping @JosiahGoeman will solve this for us.

**Comment by stephengold** [comment]
Thank you for your quick response.
How about adding a reference loop to jme3-plugins/src/test ?

**Comment by JosiahGoeman** [comment]
Looks like it was indeed that simple.  And here I was thinking my test suite was so thorough. -_-  I added a test for the reference-loop case.

**Comment by stephengold** [comment]
Thanks, @JosiahGoeman .
7f522dc passes my tests as well, so I think this PR is ready for integration---unless someone cares to review it.

**Pull request merged**
