### PR TITLE
Deprecated light node - #1033

### LINKED ISSUE #1033: deprecate the LightNode class
in favor of `LightControl` per a comment made by @pspeed42 at the Forum:
   https://hub.jmonkeyengine.org/t/bunker-lighting/41483/18

### PR DESCRIPTION
**Pull request by grizeldi**
This fixes #1033.

Should I also deprecate the TestLightNode.java?

### CODE REVIEW

**Comment by stephengold** [comment]
In the past, I've deleted tests/examples that targeted deprecated features.

**Comment by stephengold** [comment]
There are 3 `jme3-examples` apps that use `LightNode`:
 1. `TestLightNode` should be deleted.
 2. `TestConeVsFrustum` should be modified to positions the lights directly.
 3. `TestManyLightsSingle` should be modified to positions the lights directly.

**Comment by stephengold** [comment]
Stuck?

**Comment by grizeldi** [comment]
Not really, just don't have much time for coding these days. I'll try to do it asap.

**Comment by stephengold** [comment]
Just curious. No rush.

**Comment by grizeldi** [comment]
Been doing some work and figured out that TestConeVSFrustum will need some general cleanup. There are random variables that are never used and the class uses TempVars. Aren't those supposed to be used by the engine only?

**Comment by stephengold** [comment]
Yes, `TempVars` is intended only for internal use. Yes, examples should ... set a good example. However, cleanup of examples should probably go into a separate pull request unless it's clearly related to issue #1033.

**Comment by jayfella** [comment]
What is the status of this?

**Comment by grizeldi** [comment]
I think I have some more stuff done locally but never pushed it, will have to check.

**Comment by grizeldi** [comment]
Okay, looked into it a bit and I'm not sure what TestConeVSFrustum is even supposed to do. There's some unused stuff and the test as a whole looks unfinished. Still have to check TestManyLightSingle.

**Comment by stephengold** [comment]
I believe that `TestConeVSFrustrum` is supposed to test the `SpotLight.intersectsFrustum()` method. When the test is running, drag with the right mouse button pressed to reposition the spotlight's cone. When the cone no longer intersects the frustum, its color changes to grey.

**Comment by MeFisto94** [comment]
Friendly reminder to have a look at this again :)

**Comment by MeFisto94** [comment]
Yearly reminder again :D

**Pull request merged**
