### PR TITLE
Merge pull request #1 from jMonkeyEngine/master

### PR DESCRIPTION
**Pull request by MelvinsQuest**
Merge

### CODE REVIEW

**Comment by empirephoenix** [comment]
Hm, either I dont get this pull request, or 0 files are changed in it.

**Comment by MelvinsQuest** [comment]
Hey Empire. Thanks, you right, i get it wrong. Just wanted to update the jme fork on my git account from the official one. I will try to undo my commit, but if i stuck you can delete it anyway. (p.s. thanks for the jme3-javafx stuff! ;) )

**Comment by empirephoenix** [comment]
checkout your git to computer
add remote the official jme as upstream
https://help.github.com/articles/adding-a-remote/
git pull upstream master

**Comment by MelvinsQuest** [comment]
I tried with git-shell from the github-software (the repo is a fork on: https://github.com/MelvinsQuest/jmonkeyengine.git, downloaded with the said software):

E:\dev\repos\github\jmonkeyengine [master]> git remote add origin https://github
.com/jMonkeyEngine/jmonkeyengine.git
fatal: remote origin already exists.
E:\dev\repos\github\jmonkeyengine [master]> git pull upstream master
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Thanks

**Comment by MelvinsQuest** [comment]
Last time i synced the official changes with a pull request toward my fork. Maybe i should start over and reinit my repo?

**Comment by empirephoenix** [comment]
git remote add upstream https://github <- add it as upstream not origin

**Comment by MelvinsQuest** [comment]
It worked! Thanks for your patience.

**Pull request closed without merging**
