### PR TITLE
Update AppSettings.java

### PR DESCRIPTION
**Pull request by ItsMike54**
Fix for issue796 https://github.com/jMonkeyEngine/jmonkeyengine/issues/796
JOGL support was simply removed due to its unpopularity and numerous bugs.

### CODE REVIEW

**Comment by ItsMike54** [comment]
Dosen't look like anyone has commented issues with the PR; has it been long enough though to just go ahead and merge to master?

**Comment by stephengold** [comment]
There's a conflict in jme3-jogl/src/main/java/com/jme3/system/jogl/JoglContext.java that must be resolved before this PR can be integrated. @ItsMike54 please attempt to resolve the conflict.

**Comment by ItsMike54** [comment]
> There's a conflict in jme3-jogl/src/main/java/com/jme3/system/jogl/JoglContext.java that must be resolved before this PR can be integrated. @ItsMike54 please attempt to resolve the conflict.

Thank you for commenting, I'll have a look at this issue.

**Comment by ItsMike54** [comment]
Out of date, reworking it as a new PR

**Pull request closed without merging**
