### PR TITLE
opengl3: use GLSLCompat with material Lighting, Particle, ShowNormals…

### PR DESCRIPTION
**Pull request by davidB**
…, Sky

### CODE REVIEW

**Comment by Nehon** [comment]
Hey david, I'm not shure what it fixes. Could you explain?

**Comment by davidB** [comment]
It allows to use OpenGL 3.2 core with those materials.
On mac application are OpenGL 2 xor OpenGL3+ but you can't mixe. By example, Lighting.j3md is not usable with ```settings.setRenderer(AppSettings.LWJGL_OPENGL3)``` because its default technique is only for GLSL 1.1.

Is it clear ?

**Comment by davidB** [comment]
Last week-end I also should apply the same change on filter FXAA, to be able to use it with OpenGL 3 core (on mac).
Should I do update this PR, including resolve conflit, or do you plan an other approach to support Open GL 3 for material that are only defined for GLSL 100/110/120 ?

**Comment by davidB** [comment]
@Nehon , @shadowislord Any update ? There are lot of material and post-processor that are not available in Opengl 3 => un-usable with OpenGL3 core on mac or driver that didn't allow mix GLSL110 with OpenGL3 core.

**Comment by empirephoenix** [comment]
Could you explain in more detail, how this fix works? Are you basically just adding valid opengl3 techniquies? or does it change something more in the underlying?

**Comment by davidB** [comment]
It works by adding the a opengl3 techniques and the compact.glsl lib made by Kirill.

* same as https://github.com/jMonkeyEngine/jmonkeyengine/pull/377
* discussion start  in https://github.com/jMonkeyEngine/jmonkeyengine/pull/288

**Comment by empirephoenix** [comment]
So I kinda tend to merge by now, as more than enough time was given for protest and it should not break anything, but allow mac , but it has merge conflicts :)

**Comment by empirephoenix** [comment]
Closed due to being dead

**Pull request closed without merging**
