### PR TITLE
Add support for opengl versions > 3.2 in lwjgl2 renderer

### PR DESCRIPTION
**Pull request by riccardobl**

### CODE REVIEW

**Comment by grizeldi** [comment]
Tested it and versions above 3.2 no longer throw an exception. The opengl version logged on application launch seems in sync with the forced version, so this is probably good to merge.

**Comment by riccardobl** [comment]
@Ali-RS Check if you are happy now, if not provide a formatter setting

**Comment by Ali-RS** [comment]
Seems you missed  one line :
https://github.com/jMonkeyEngine/jmonkeyengine/blob/1e093fec87f1eb0769c2572733af43e6e5ba120d/jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java#L162

**Comment by riccardobl** [comment]
amended

**Comment by Ali-RS** [comment]
Thanks Riccardo.

**Comment by Ali-RS** [comment]
@riccardobl which formatting were you using for your PR? 
I have never seen some formatting like this `vers!=null&&vers[0]!=2` before. 
Is it your own preference or is it done by your IDE? I am pretty sure neither Eclipse nor Netbeans uses this standard?

**Comment by riccardobl** [comment]
No formatting, i just typed it that way :smile:

**Pull request merged**
