### PR TITLE
userdata to null again once all data is removed.

### PR DESCRIPTION
**Pull request by NemesisMate**
Discussion about: https://hub.jmonkeyengine.org/t/userdata-map-not-going-back-to-null-value-once-any-data-is-set/36236

### CODE REVIEW

**Comment by empirephoenix** [comment]
lets wait a few days to see if someone wants to input something, else I will merge

**Comment by gouessej** [comment]
Please improve your change. Currently, if userData is null before calling setUserData("any_key", null), the hashmap is created at the beginning whereas it is useless as you're going to drop it a few lines later. I'd rather write:
```
if (data == null) {
    if (userData != null) {
         userData.remove(key);
         if(userData.isEmpty()) {
             userData = null;
         }
    }
} else {
     if (userData == null) {
         userData = new HashMap<String, Savable>();
     }
     if (data instanceof Savable) {
         userData.put(key, (Savable) data);
     } else {
          userData.put(key, new UserData(UserData.getObjectType(data), data));
     }
}
```

**Comment by Nehon** [comment]
I agree with you Julien. Though it's a bit out of the scope of this PR, because what you describe is the behaviour we have today, regardless of this PR.

Also, calling setUserData("any_key", null) when the userData is empty is not in the normal usage flow of  user data, usually, you want to delete things from a non empty list.

So basically, no big deal if it's merged like this. Though, If OP wants to jump on the occasion to refactor a bit and clean up the code, I'm fine with it too.

**Comment by NemesisMate** [comment]
You are right, Julien, I think I was a little careless, thanks.

**Comment by gouessej** [comment]
You're welcome. I didn't want your stuff to be rejected, I preferred suggesting a small change. Now it's ok for me of course.

**Comment by empirephoenix** [comment]
Thanks for the work.

**Pull request merged**
