### PR TITLE
Removed unused imports.

### PR DESCRIPTION
**Pull request by Ali-RS**
Done with Netbeans `Inspect and Transform` tool.

### CODE REVIEW

**Comment by Ali-RS** [comment]
Thank you Stephen :)

**Comment by quazi-irfan** [comment]
I was wondering why Travis didn't trigger in this pull request. I was under the assumption that Travis is triggered with all pull requests.

**Comment by stephengold** [comment]
It looks to me like Travis ran on the pull request and again on the commit I integrated. Why do you believe it wasn't triggered?

**Comment by stephengold** [comment]
https://travis-ci.org/jMonkeyEngine/jmonkeyengine/builds/491477131

https://travis-ci.org/jMonkeyEngine/jmonkeyengine/builds/491990814

**Comment by quazi-irfan** [comment]
I usually see the green notification saying 'all checks have passed' in each pull request(see screenshot), but I do not see it with this one. Is it seen by only those who submitted the pull request?

image

**Comment by pspeed42** [comment]
I think maybe when it's been merged it goes away.

**Pull request merged**
