### PR TITLE
Fix title (and registry entry) for Settingsdialog

### PR DESCRIPTION
**Pull request by Pesegato**
...the developer probably want it to be named as its application

### CODE REVIEW

**Comment by stephengold** [comment]
I haven't forgotten about this PR. I just need some focused time to think about it.

**Comment by stephengold** [comment]
I don't understand the motivation for this PR.

When I run a JME application named "Maud", I expect the settings dialog to have the title "Display Settings for Maud" and the application window to have the title "Maud". And that's exactly what I see in practice. Are you seeing something different?

**Comment by Pesegato** [comment]
If you delete the registry entries and start from scratch, then you won't see "Maud".

**Comment by stephengold** [comment]
My JME applications explicitly set the window title in `main()` like so:
```java
        AppSettings settings = new AppSettings(true);
        settings.setTitle(windowTitle);
        application.setSettings(settings);

        application.start();
```

You're proposing that JME should override that setting?

**Comment by Pesegato** [comment]
Moving the discussion to the forum

https://hub.jmonkeyengine.org/t/pr1580/45105

**Pull request closed without merging**
