### PR TITLE
 using deprecated FrameBuffer methods in jme3-core and jme3-desktop #1657 

### PR DESCRIPTION
**Pull request by bob0bob**
Updating all references to setDepthTexture  and setColorTexture from old system to the new system.

### CODE REVIEW

**Comment by stephengold** [comment]
Please go back check for unused imports in the files you modified.

**Comment by bob0bob** [comment]
They are removed.

**Comment by stephengold** [comment]
Codacy thinks there are still 2 new unused imports in AbstractShadowRendererVR.java
Please take another look.

**Comment by bob0bob** [comment]
What 2 imports.  My environment doesn't show any unused. I see 2 in AbstractShadowFilterVR.java

**Comment by stephengold** [comment]
com.jme3.texture.FrameBuffer.FrameBufferBufferTarget
com.jme3.texture.FrameBuffer.FrameBufferTextureTarget
both in AbstractShadowRendererVR.java (not AbstractShadowFilterVR.java)

**Comment by bob0bob** [comment]
Got looking at wrong branch.

**Comment by stephengold** [comment]
The code formatting is inconsistent, but it'll be easier for me to fix that directly during integration than to explain precisely what I want changed.

I'm uneasy about adding static methods to the `FrameBufferTarget` class. I suspect that's not what @riccardobl had in mind when he deprecated `setDepthTexture()` and `setColorTexture()`. However, I haven't come up with a better solution, so it'll have to do.

My biggest concern is test coverage. What tests have you run with these changes?

> Got looking at wrong branch.

That happens to me often. You have my sympathy.

**Comment by bob0bob** [comment]
do you guys have a document on formatting requirements.  I know many people have profiles for different environments so you can use that directly and it has the same style.
I didn't see anything like that.

**Comment by stephengold** [comment]
> do you guys have a document on formatting requirements. I know many people have profiles for different environments so you can use that directly and it has the same style. I didn't see anything like that.

We recently added Java style guidelines to [CONTRIBUTING.md](https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/CONTRIBUTING.md#coding-style). It's basically Google style with a handful of local mods. It covers formatting as well as other style issues such as naming and javadoc.

**Comment by stephengold** [comment]
What tests have you run with these changes?

**Comment by bob0bob** [comment]
I would test .  I ran them against all the test applications that where altered.  
Then a FrameBuffer examples and a water example.

That should about cover it all.

**Comment by stephengold** [comment]
Alright, then. Thanks for your contribution!

**Pull request merged**
