### PR TITLE
LodGenerator should accept a constructor by mesh

### PR DESCRIPTION
**Pull request by mazerty**

### CODE REVIEW

**Comment by empirephoenix** [comment]
Yep you are right, I will merge this once build is finished

**Comment by mazerty** [comment]
perfect :) thank you !

**Comment by mazerty** [comment]
isn't there a problem with travis ? the build shouldn't fail like this right ? :(

**Comment by empirephoenix** [comment]
Build delays and API issues affecting travis-ci.com, i would say we give it some time, and then retry the build

**Comment by mazerty** [comment]
do you know how to retry the build without commiting anything new ? maybe i should cancel the pull request and create it again ?

**Comment by empirephoenix** [comment]
Yes, that might be the fastest and cleanest way, please do so.

**Pull request closed without merging**
