### PR TITLE
Add getSpatial to GhostControl, RigidBodyControl, AbstractPhysicsCont…

### PR DESCRIPTION
**Pull request by quazi-irfan**
…rol and CharacterControl. Fix issue #1008

### CODE REVIEW

**Comment by stephengold** [comment]
Nice work.

One correction: spatials are not attached to controls; controls are added to spatials. Could you please change the javadoc accordingly?

**Comment by quazi-irfan** [comment]
It there a way to write it more clearly? I am not sure if it's the best way to write it.

**Comment by stephengold** [comment]
The way you have it is okay.
Note how the field is documented above:
```
    /**
     * spatial to which this control is added, or null if none
     */
```

**Comment by quazi-irfan** [comment]
Then perhaps the doc should say, `returns the spatial the control is added to, or null if control is not attached to a spatial yet.`

**Comment by stephengold** [comment]
Sure. Sounds good.

**Comment by stephengold** [comment]
Okay, I think this is ready to integrate. I'll leave it open another day in case anyone else wants to review it.

**Comment by tlf30** [comment]
Looks good to me!

**Pull request merged**
