### PR TITLE
Build android bullet-native on Travis

### PR DESCRIPTION
**Pull request by MeFisto94**
See #1171 for details. Note that #1171 has to be merged first (as this PR is based on it).
Also note that the deployment has to be thought of much like with #1171.
This also touches jme3-bullet-native, which should now compile a bit faster and cleaner (no intermediary files and two-pass-compilation).

Actually I wonder If I should re-open this PR once #1171 is merged into core, so this PR only contains one Commit?

### CODE REVIEW

**Comment by stephengold** [comment]
The conflict resolution look trivial, but I'll leave you to decide whether to resolve it or create a new PR.

**Comment by MeFisto94** [comment]
Odd. Now AppVeyor is run and fails for a good reason. I'll look into it.

**Comment by stephengold** [comment]
Is this ready for integration?

**Comment by MeFisto94** [comment]
It's ready, the deployment changes can then be done together with #1171.

**Pull request merged**
