### PR TITLE
Update gradle wrapper to 8.8

### LINKED ISSUE #2287: Gradle Upgrade
Gradle hasn't been upgraded in a while.

Issue tracking upgrading gradle, to support newer java versions

### PR DESCRIPTION
**Pull request by 8Keep**
Fix #2287

### CODE REVIEW

**Comment by stephengold** [comment]
Did you follow the [documented update procedure](https://docs.gradle.org/8.8/userguide/upgrading_version_8.html)?

**Comment by 8Keep** [comment]
I didn't read the whole doc, most of it is irrelevant to us, but yeah that's pretty much what I did.

**Comment by stephengold** [comment]
Running `gradlew wrapper --gradle-version=8.8` modifies the following files:
+ gradle/wrapper/gradle-wrapper.jar
+ gradle/wrapper/gradle-wrapper.properties
+ gradlew
+ gradlew.bat

Please include those change in this PR.

**Comment by stephengold** [comment]
I've reviewed the changes and don't see any problems. However, a change like this needs thorough testing more than it needs human review. I'm curious how much testing has been done so far:

+ platforms (Android, Linux, macOS, and Windows)?
+ tasks ("build", "clean", "dist", "install", "release", "mergedJavadoc", "mergedSource", "createZipDistribution", "copyLibs")?
+ command-line options ("-PuseCommitHashAsVersionName", "-PbuildNativeProjects", "-PskipPrebuildLibraries")?

**Comment by stephengold** [comment]
@8Keep I remain curious.

**Comment by 8Keep** [comment]
Let me try these later today. We should also run these in CI, I'm surprised that we don't already.

**Comment by 8Keep** [comment]
@stephengold  I've ran all the tasks you've sent, except release, because that doesn't exist. Unless you meant publish, which I can't finish due to not having a key. publishToMavenLocal does succeed.

copyLibs needed an update on line 117 of build.gradle. The thing is that according to some online sources, this was changed with gradle 7, so it may not have worked ever since the gradle 7 upgrade was done.

**Comment by stephengold** [comment]
Good progress, thank you.

> I've ran all the tasks you've sent, except release, because that doesn't exist. Unless you meant publish, which I can't finish due to not having a key. publishToMavenLocal does succeed.

You're right: I was thinking of the publish tasks. Since "publishToMavenLocal" succeeded, there's a high probability that "publishMavenPublicationToSNAPSHOTRepository" and "publishMavenPublicationToOSSRHRepository" will also work.

I think this PR is ready for integration into the "master" branch. Do you agree?

**Comment by 8Keep** [comment]
Yes, I agree. I want to do some followups, but I'll start these in separate prs:

1) Start running a java 21 build in CI
2) Start running more in CI to test all the tasks
3) Start getting rid of deprecated gradle features in the build, so the upgrade to gradle 9 goes smoothly

**Comment by 8Keep** [comment]
It looks like publishing natives did fail once it was committed. Stephen do you know what is the implications of this error:

https://github.com/jMonkeyEngine/jmonkeyengine/actions/runs/9820622481/job/27115496415#step:5:549

**Comment by stephengold** [comment]
I think it's related to a change at Sonatype. On 11 June, I got a cryptic e-mail from them about updating our plugin settings. Maybe those changes took effect sometime between 3 July and now?

I've generated Sonatype user tokens before, for my personal repos. I don't want to do it tonight when I'm tired. I'll investigate further tomorrow when I'm fresh.

**Comment by stephengold** [comment]
And now I see the CI for 5248fb0c1372eb00df9a666ab7881176eb4cdcb0 succeeded, so perhaps it was just a transient network error. Let's wait and see whether it recurs.

**Comment by stephengold** [comment]
I believe this was the change that caused issue #2335

**Pull request merged**
