### PR TITLE
support Android assets paths starting with /

### PR DESCRIPTION
**Pull request by scenemax3d**

### CODE REVIEW

**Comment by Ali-RS** [comment]
Looks fine to me.

**Comment by stephengold** [comment]
Please explain the issue addressed by this PR in more detail. Why would an Android asset path contain consecutive slashes?

**Comment by scenemax3d** [comment]
> Please explain the issue addressed by this PR in more detail. Why would an Android asset path contain consecutive slashes?

When DesktopAssetsManager registers its locators, it sets a slash **rootPath** for each locator including AndroidLocator. Combine that with assets path which begins with a slash and the current slash cleaning code in the locator's locate method cannot cope with it because it assumes no more than one slash in the beginning of the path.

**Comment by tlf30** [comment]
This is an interesting issue. I feel like others including myself would have run into before. Can you please provide a simple test case?

**Comment by scenemax3d** [comment]
> This is an interesting issue. I feel like others including myself would have run into before. Can you please provide a simple test case?

Put any asset in your application's assets folder, for example: **assets/Textures/my_icon.png**
The try to load it in your JME application: assetManager.loadTexture("**/**Textures/my_icon.png"); notice the **slash** in the beginning of the path...
**result**: no locator including AndroidLocator will be able to locate this texture

**Review by stephengold — APPROVED** [review]

**Comment by MeFisto94** [comment]
> result: no locator including AndroidLocator will be able to locate this texture

So this is also an issue for desktop? if so, that may need a solution at another place, though I wonder if the code was ever meant to support leading `/` paths, because jme examples never have that, afaik.

If that's a goal, it's also important to note that unit tests may be wanted for that, writing one for that is trivial.

**Comment by stephengold** [comment]
It's not an issue for desktops, because the jme-vehicles project uses such asset paths, and it works on desktops.

**Comment by neph1** [comment]
Related it seems: [https://github.com/jMonkeyEngine/jmonkeyengine/issues/352](https://github.com/jMonkeyEngine/jmonkeyengine/issues/352)

**Comment by stephengold** [comment]
Good catch, @neph1 !

**Pull request merged**
