### PR TITLE
Refactoring upgrading lwjgl3 v.3

### PR DESCRIPTION
**Pull request by JavaSaBr**
A compacted version of this PR:
https://github.com/jMonkeyEngine/jmonkeyengine/pull/790

### CODE REVIEW

**Comment by JavaSaBr** [comment]
@Nehon attempt #3 :)

**Comment by JavaSaBr** [comment]
@Nehon anything else?

**Comment by AlrikG** [comment]
Hi JavaSaBr,
Sorry if you've already answered this question somewhere, but why did you remove the public access modifier from the GL class's statics and methods?

**Comment by JavaSaBr** [comment]
Hi, because the public is default access for interfaces.

**Comment by AlrikG** [comment]
Ok thanks :) I overlooked that. But this also means that you can remove the static and final modifiers from constants. Am I right? => https://docs.oracle.com/javase/tutorial/java/IandI/interfaceDef.html

**Comment by pspeed42** [comment]
Did you read back where we had him put it back because we prefer it the verbose way in this case?
a) it's easier to cut-paste
b) it's easier to grep/search through code
c) it avoids conversations like these where you have to point to the spec to prove that you can do it.

**Comment by AlrikG** [comment]
No sorry I only looked into the changes instead of the PR #790

**Pull request merged**
