### PR TITLE
#1569 Fix license file to be better detected by GitHub

### PR DESCRIPTION
**Pull request by b0n541**
Rename source file header template

### CODE REVIEW

**Comment by b0n541** [comment]
@stephengold one build step failed for no obvious reason. Could you trigger a re-start, please.

**Comment by b0n541** [comment]
Is anything else needed to be done from my side here? 

If not and this can't merged right now, would you be so kind and add at least the label "hacktoberfest-accepted" to this pull request?

**Comment by stephengold** [comment]
@riccardobl this is a Hacktoberfest PR. Please review it and respond to the submittor.

**Comment by riccardobl** [comment]
> Is anything else needed to be done from my side here?
> 
> If not and this can't merged right now, would you be so kind and add at least the label "hacktoberfest-accepted" to this pull request, please?

Merged. Thank you for taking the time to figure this out.

**Pull request merged**
