### PR TITLE
fixed NPE when you try to remove an unused asset loader.

### PR DESCRIPTION
**Pull request by JavaSaBr**
Fixed NPE when you try to remove an unused asset loader.

### CODE REVIEW

**Comment by JavaSaBr** [comment]
@shadowislord @Nehon @empirephoenix could you review this change, please?

**Comment by empirephoenix** [comment]
Looks fine to me, 
since you are already at it, couldnt those two be combined?

            ImplThreadLocal local = classToLoaderMap.get(loaderType);
 classToLoaderMap.remove(loaderType);

if I remember right remove will return a removed item already?

**Comment by JavaSaBr** [comment]
@empirephoenix I agree, I have updated it.

**Comment by empirephoenix** [comment]
Thanks for your work :)

**Pull request merged**
