### PR TITLE
Unnecessary Asset Addition - Learning Github

### PR DESCRIPTION
**Pull request by Relic724**
Yeah, I just need to make sure that I can actually figure out one of
these pull request thingies I keep hearing about.

Make sure to say "howdy"! :smile:   And then, just deny it or whatever.
I'll try to figure out how to remove this if you guys can't.  <-- still
learning, me.

So ... hope hope hope.... LOL

### CODE REVIEW

**Comment by Relic724** [comment]
I guess this is where we make the conversation at on this site? I know that I receive emails on the other pull requests n Merges ...

**Comment by Relic724** [comment]
I am just needing anyone from core to say anything.  I don't know if this shows up for your viewing pleasure due to instances where I think that I am doing something... and it's in the wrong place... 
I may have miscommunicated my purpose... This is to establish, to myself, as to how to properly work with Github. so that I can help out in the future....

So... 
Hello, is anyone out there?

**Comment by shadowislord** [comment]
Seems to work OK from here.

**Comment by Relic724** [comment]
Ok! Thanks Kirill! Closing... this ... then... Where's that button?

glarg .... oh... there it is.

Game On!
Charles

**Comment by NetzwergX** [comment]
There is an official learning repository that you can use to test out pull requests and such:
https://github.com/octocat/Spoon-Knife ;)

**Pull request closed without merging**
