### PR TITLE
Add simple math methods to Vector3f

### PR DESCRIPTION
**Pull request by yaRnMcDonuts**
I've added these convenience multiplication and division methods that were missing from the Vector3f class, and did my best to also follow the same javadoc formatting that the rest of the similar methods have. 

Let me know if this looks alright and then I will do the same for Vector2f and Vector4f. And should I make the changes to Vector2f and Vector4f in this PR or should I make a new PR for each?

### CODE REVIEW

**Comment by stephengold** [comment]
> should I make the changes to Vector2f and Vector4f in this PR or should I make a new PR for each?

Either way is fine.

**Comment by stephengold** [comment]
Looks good so far.

**Comment by stephengold** [comment]
Unless there's more to discuss, I plan to integrate this to "master" in about 24 hours.

**Comment by stephengold** [comment]
Thanks for your contribution, @yaRnMcDonuts.

**Comment by yaRnMcDonuts** [comment]
Glad to contribute whenever I can

**Pull request merged**
