### PR TITLE
FBX Importer fixes and updates

### PR DESCRIPTION
**Pull request by Eirenliel**
Here is the original topic: https://hub.jmonkeyengine.org/t/fbx-importer/30309

Changes:

* Added support of FBX 2016-17 (7.5)
* Fixed rotation orders (reverse the order, use only for Lcl Rotation)
* Fixed animations transformation (proper conversion from parent space to bone space, proper use of rotation order and other transforms)
* Implemented Segment Scale Compensate property from Maya (most cases) aka InheritType
* Implemented loading bind pose from frame 0
* Properly load all animations from animation layers
* Reworked units size (still no program uses it properly to test)
* Tons of testing with animations and different models

### CODE REVIEW

**Comment by JavaSaBr** [comment]
Cool!

**Comment by Ali-RS** [comment]
Awesome :smiley:

**Comment by bensku** [comment]
Awesome!

**Comment by empirephoenix** [comment]
Does anyone of you uses FBX, and can validate that it does not break existing stuff badly? Since I'm not using FBX, I'm a bit carefull with directly merging it.

**Comment by Eirenliel** [comment]
@bensku no, it's not since previous version

**Comment by bensku** [comment]
Oh. Didn't notice that. Very good!

**Comment by bensku** [comment]
<code>java.lang.NullPointerException
	at com.jme3.scene.plugins.fbx.mesh.FbxMesh.applyCluster(FbxMesh.java:127)
	at com.jme3.scene.plugins.fbx.mesh.FbxMesh.toJmeObject(FbxMesh.java:213)
	at com.jme3.scene.plugins.fbx.mesh.FbxMesh.toJmeObject(FbxMesh.java:58)
	at com.jme3.scene.plugins.fbx.obj.FbxObject.getJmeObject(FbxObject.java:113)
	at com.jme3.scene.plugins.fbx.node.FbxNode.toJmeObject(FbxNode.java:399)
	at com.jme3.scene.plugins.fbx.node.FbxNode.toJmeObject(FbxNode.java:71)
	at com.jme3.scene.plugins.fbx.obj.FbxObject.getJmeObject(FbxObject.java:113)
	at com.jme3.scene.plugins.fbx.node.FbxNode.createScene(FbxNode.java:496)
	at com.jme3.scene.plugins.fbx.node.FbxNode.createScene(FbxNode.java:503)
	at com.jme3.scene.plugins.fbx.node.FbxNode.createScene(FbxNode.java:503)
	at com.jme3.scene.plugins.fbx.node.FbxNode.createScene(FbxNode.java:503)
	at com.jme3.scene.plugins.fbx.FbxLoader.constructSceneGraph(FbxLoader.java:406)
	at com.jme3.scene.plugins.fbx.FbxLoader.load(FbxLoader.java:126)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	<redacted my application's stack trace>
	at com.jme3.app.state.AppStateManager.initializePending(AppStateManager.java:251)
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:281)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:236)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:745)
</code>
This happens when trying to load one rather complex scene exporter from Blender 2.7.8. It happens with older version too, though.

**Comment by Eirenliel** [comment]
Can you attach the file, please?

**Comment by Eirenliel** [comment]
@bensku you're testing wrong importer ;)
This patch is about `com.jme3.scene.plugins.fbx.SceneLoader`

**Comment by bensku** [comment]
Oh, that explains a lot :) No wonder why it didn't work...

I guess I need to register SceneLoader to be associated with FBX manually.

**Comment by Eirenliel** [comment]
@bensku you can just edit Desktop.cfg

**Comment by JavaSaBr** [comment]
Are you going to merge it? :)

**Comment by Nehon** [comment]
@shadowislord Could you review this?

**Comment by Ali-RS** [comment]
Yesterday I grabbed a few fbx model, I want to test this new fbx loader.
A bit hard to copy paste the code from here to my fork, so will appreciate you if you can merge this commit to a temporary branch so I can build from it locally. 
Thanks

**Comment by empirephoenix** [comment]
You can just clone https://github.com/Heatherglade/jmonkeyengine (see the line with the link above the all checks passed)

**Comment by Nehon** [comment]
A pull request is essentially a branch, you just have to pull it
https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by empirephoenix** [comment]
So nay news on testing this?

**Comment by Ali-RS** [comment]
Sorry for late reply 
Finally I found some time to test new fbx loader. 
I tested an animated fbx model which exported from blender. (fbx binary 7400 version) but the animation was broken. (the animation was stretched on arms and legs). 
I do not use Maya, so I could not test it. 
@Eirenliel  have you tried an fbx model exported from blender ?

**Comment by Eirenliel** [comment]
@Ali-RS we are not working with Blender, we are working with Maya. I also do know that some stuff Blender _imports_ from FBX wrong, but not necessary this case.

We recently made another giant update for FBX importer, i will share it a bit later, so this pull request can be just closed. Also can you send the file you are talking about for us to test in the new version?

**Comment by empirephoenix** [comment]
Ok, closed as per request, :+1: for next request :)

**Comment by Ali-RS** [comment]
> Also can you send the file you are talking about for us to test in the new version?

Yes, you can get it here : 
https://drive.google.com/open?id=0B35eWZpi0dBoZmtwNjdRUGp6Skk

**Comment by Ali-RS** [comment]
Also, what bone rotation mode does your fbx loader support ?
Quaternion(WXYZ)  or XYZ Euler or ... ?

**Comment by Eirenliel** [comment]
@Ali-RS i've never seen quaternion rotation in real files, so i don't think it supports it now. I will check the provided file.

**Comment by Ali-RS** [comment]
Okay.
Can you please test these two fbx files also : https://drive.google.com/open?id=0B35eWZpi0dBoVTZ1MlVBTTZpaUE

I have followed this tutorial for exporting them from blender : http://digitalrune.github.io/DigitalRune-Documentation/html/6f749972-9cb2-4274-b283-c327ba45e379.htm so i am pretty sure they standard fbx formats.

in one of them i enabled **!EXPERIMENTAL! Apply Transform**  when exporting and in the other one not.
I am getting diffrent result for each one in jme. 
I hope they play fine in your code :)

**Comment by Eirenliel** [comment]
@Ali-RS all of this files have problems when importing. We will see why when we have time, thanks :)

**Comment by Ali-RS** [comment]
Thank you.

**Comment by deltasquad451** [comment]
@Eirenliel I seem to be getting an issue with the animations not playing properly, I have a model created in MayaLT with a walk animation.
Here it is in MayaLT:
mayawalk_2017_05_08_14 37 18

When I import the model with Jmonkey I get the following:
jmonkey_2017_05_08_14 37 22

Here is the model in question:
https://drive.google.com/file/d/0B24ekh4abl8CTEhYeVFmZDZfTWM/view?usp=sharing

**Comment by Eirenliel** [comment]
@deltasquad451 thank you, we will test it. We are working on fixing importer for our game on a daily basis, but it's an active development, so i don't know when we will be ready and have time to try to move it to JME, but it will happen any time soon :)

**Comment by Pilvinen** [comment]
@Eirenliel Any news on the above with deltasquad451? This is currently a major blocker for our project and has been for quite some time. We were already considering switching to Unity because we haven't found a way to get our models working. But we really don't want to do that if there's a possibility to get things working.

**Comment by JavaSaBr** [comment]
@Pilvinen I think you can open .fbx in Blender and then save it like a .xbuf file which has good support from jME :)
https://github.com/xbuf/xbuf
.xbuf have no problems with animation on jME.

**Comment by Eirenliel** [comment]
@Pilvinen sorry we currently can't make necessary checks and prepare commits in jME.

**Comment by Pilvinen** [comment]
@JavaSaBr Unfortunately it's not possible. Blender messes up the rig on import.
@Eirenliel Give me an estimate so I can make educated decision where to take my project to which I've invested considerable amount of time and money. 1 months, 2 months, 4 months, 6 months, 12 months, 24 months, never?

**Comment by JavaSaBr** [comment]
@Pilvinen do you think we have no any format which has good support for both programs?

**Comment by Pilvinen** [comment]
@JavaSaBr Unfortunately Maya LT supports only .OBJ, .FBX and .mayaLT. It's Autodesk's way of saying "screw you" to indie developers who can't afford Maya full. 

.blend support is good in Jmonkey but this whole Maya <--> Blender and Jmonkey <--> Maya inoperability has really screwed us over. We've tried all kinds of magic tricks for several months and we simply don't have a way to get our rigged and animated models to Jmonkey.

Had we known this would be such an huge issue from the start we might have chosen differently, but we're now one year into development and frankly I'm at the end of my wits with this issue.

FBX in a very unfortunate closed format industry standard - but the situation is what it is. Most of the animators out there use Maya or some other Autodesk product - and you guessed it - they all export FBX. Importing to Blender is a no-go otherwise we would simply do it like that and export .blend from Blender.

I don't know what to do.

**Comment by JavaSaBr** [comment]
@Pilvinen did you check this addon?
http://amyaimei.deviantart.com/art/Bos-FBX-Importer-Exporter-for-Blender-2-77-Win64-621287370

**Comment by JavaSaBr** [comment]
@Pilvinen 
http://growlybearproductions.com/Blender/

**Comment by deltasquad451** [comment]
@JavaSaBr Does the Bos FBX  support animations though?

**Comment by JavaSaBr** [comment]
@deltasquad451 I don't know

**Comment by Pilvinen** [comment]
@JavaSaBr This happens with Blender. Unfortunately it's not only the mesh but as you can see the bones are all messed up too, scale and everything. It's hopeless.

@deltasquad451 did play around with BOS FBX but was unable to get it working with that either. It was some time ago so I can't remember all the details of what happened.

Growlybearproductions link I haven't seen before but it seems he only had problems with the mesh orientation and scale - and if you take a look at the screenshot I provided from my Blender FBX import adventures you can see it's hopelessly messed up and not just rotation and scale issue. The animation is there but it's... very funky.

**Comment by JavaSaBr** [comment]
@Perjin my artist who works in Blender have advice:
https://help.sketchfab.com/hc/en-us/articles/206223646-Blender-Animation#fbx

**Comment by Eirenliel** [comment]
@Pilvinen again all i can say is sorry, we are pretty swamped right now and if i try to give any estimate on plans, it might be wrong by any magnitude...

**Comment by Eirenliel** [comment]
@Pilvinen but i tested the file you send and it does have some issues with animation. Sadly, we have no time to investigate it further :(

**Pull request closed without merging**
