### PR TITLE
fix for #1106

### PR DESCRIPTION
**Pull request by rvandoosselaer**
when the image object has a ColorSpace value we pass it on, else we leave it at the default value.

### CODE REVIEW

**Comment by stephengold** [comment]
I had hoped for some review by a more senior monkey, but seem to know what you're doing.

**Comment by rvandoosselaer** [comment]
I did a few tests with my own models and some free one’s I found online. I didn’t encountered any errors or strange behaviour, it seems to work.
However if people do find issues with it, I’ll be happy to revert the change or look for a solution.

**Comment by riccardobl** [comment]
Ok, sorry i didn't see this (it might be a good idea for the future to use an actual title for PRs, because when you start having several "Fix *ISSUE NUMBER*" it's easy to miss some).

My question is, what will happen if i have a matdef that defines a -LINEAR param, but the image is sRGB? Will this pr break the linearization by forcing the mat param to become -LINEAR ?

**Comment by rvandoosselaer** [comment]
> Ok, sorry i didn't see this (it might be a good idea for the future to use an actual title for PRs, because when you start having several "Fix _ISSUE NUMBER_" it's easy to miss some).
> 
> My question is, what will happen if i have a matdef that defines a -LINEAR param, but the image is sRGB? Will this pr break the linearization by forcing the mat param to become sRGB ?

Hi @riccardobl, I wasn't aware of the -LINEAR option in a material definition file.
I just tested it, and if you specify -LINEAR in the materialDef, the colorspace _will_ be set to linear.

This is my test case:
Gamma correction is enabled, the texture in the material is an sRGB one, the colorspace in the materialDef is set to '-LINEAR':
Screenshot 2019-06-26 at 21 00 46
I also added a log statement printing out the colorspace of the material that is set on the model:
From the log:
Colorspace: Linear

Same test as above, but without the -LINEAR flag:
Screenshot 2019-06-26 at 21 02 57
log:
Colorspace: sRGB

The first image is clearly gamma corrected (too bright) because of the colorspace, so all should still be working as expected.

**Comment by riccardobl** [comment]
Can you share the code?

**Comment by rvandoosselaer** [comment]
test:

```java
public class TestMaterialLinearColorspace extends SimpleApplication {

    public static void main(String[] args) {
        new TestMaterialLinearColorspace().start();
    }

    @Override
    public void simpleInitApp() {
        AmbientLight ambientLight = new AmbientLight(ColorRGBA.White.mult(0.2f));
        DirectionalLight directionalLight = new DirectionalLight(new Vector3f(-0.2f, -1, -0.2f).normalizeLocal(), ColorRGBA.White);

        Spatial model = assetManager.loadModel("staff-0.j3o");
        Material material = assetManager.loadMaterial("colorspace-test.j3m");
        model.depthFirstTraversal(new SceneGraphVisitorAdapter() {
            @Override
            public void visit(Geometry geom) {
                geom.setMaterial(material);
                System.out.println("Colorspace: " + material.getTextureParam("DiffuseMap").getColorSpace());
            }
        });

        rootNode.addLight(ambientLight);
        rootNode.addLight(directionalLight);
        rootNode.attachChild(model);
    }
}
```

material:
```
Material colorsapace-test : Common/MatDefs/Light/Lighting.j3md {
    MaterialParameters {
        Shininess: 0
        UseMaterialColors: true
        DiffuseMap: Flip texture.png
        Ambient: 1.0 1.0 1.0 1.0
        Diffuse: 1.0 1.0 1.0 1.0
        Specular: 0.0 0.0 0.0 1.0
    }
}
```

When running the testcase, I adapted this line in `Lighting.j3md`:
```
// Diffuse map
Texture2D DiffuseMap
```

to:

```
// Diffuse map
Texture2D DiffuseMap -LINEAR
```

If you want I can create a proper testcase for it, and put it in the jme3-examples module.

**Comment by riccardobl** [comment]
Oh ok, i see.  I was mislead by the fact that both Materials and MatDefs keep a list of MatParamTexture. But the material will always look at the matdef list to see if it needs to switch the colorspace.

**Comment by rvandoosselaer** [comment]
> Oh ok, i see. I was mislead by the fact that both Materials and MatDefs keep a list of MatParamTexture. But the material will always look at the matdef list to see if it needs to switch the colorspace.

Yep, indeed.

**Pull request merged**
