### PR TITLE
Autoformat workflow

### PR DESCRIPTION
**Pull request by riccardobl**
A github action workflow that applies [prettifier](https://prettier.io/) to pull requests (if needed) to automatically fix formatting issues.

## Why prettifier?
- It is standalone
- The rules are similar to jme style but standardized (the only custom option used is tabsize=4)
- It is supported by many editors and can be used as git pre commit hook
- It supports many languages 

The goal is to make pr integration faster by resolving all sort of formatting issues automatically, since sometimes, even with a properly configured editor it is possible to miss some. (Unless you configure your editor to format on save, but can pollute the commit since most of our code was not formatted properly from the start.).

With this workflow contributors can simply pr changes  and have github action attach a formatting commit for the changed files, only if necessary.

I won't hide the fact that i am proposing this also because i am starting to believe i have developed some form of *formatting blindness*, since despite putting in 101% effort my PRs  always have formatting issues :crab: .

### CODE REVIEW

**Comment by riccardobl** [comment]
If there aren't objections i will merge this

**Comment by stephengold** [comment]
Go ahead and integrate it. If it causes problems, we can simply delete the workflow, right?

**Comment by Ali-RS** [comment]
Shouldn't we first test this in a separate branch with a dummy PR?

**Comment by riccardobl** [comment]
> Go ahead and integrate it. If it causes problems, we can simply delete the workflow, right?

Yes



> Shall we test this in a separate branch with a dummy PR first? Just to see if it works fine before applying it on real PRs.

I've tested it here https://github.com/RiccardoblSandbox/jmonkeyengine-test .
I increased the suggested line width to 180 (that's the same of our jme_style.xml)  because it was breaking the lines too easily

**Comment by Ali-RS** [comment]
Do we prefer this
```
    public BulletAppState(
        Vector3f worldMin,
        Vector3f worldMax,
        BroadphaseType broadphaseType
    ) {
```
over this?

```
public BulletAppState(Vector3f worldMin, Vector3f worldMax, BroadphaseType broadphaseType) {
```

or was that because of the line length setting you mentioned above

**Comment by stephengold** [comment]
I think the maximum line length should be 110 characters/columns, per our preferred coding style: https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/CONTRIBUTING.md#coding-style

**Comment by riccardobl** [comment]
> or was that because of the line length setting you mentioned above?

This is the formatting with line width = 110

https://github.com/RiccardoblSandbox/jmonkeyengine-test/pull/12/commits/65454e2526be418251e3b13aa258050f377ee08c



> I think the maximum line length should be 110 characters/columns, per our preferred coding style: https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/CONTRIBUTING.md#coding-style

Done, it seems JME_style.xml has some errors

**Comment by Ali-RS** [comment]
>This is the formatting with line width = 110

I see, it looks better now.

**Comment by riccardobl** [comment]
> > This is the formatting with line width = 110
> > [RiccardoblSandbox@65454e2](https://github.com/RiccardoblSandbox/jmonkeyengine-test/commit/65454e2526be418251e3b13aa258050f377ee08c)
> 
> I think it looks better now, thanks.
> 
> What was the default width used by the plugin?

it uses 80

**Comment by stephengold** [comment]
Is there any reason to retain the "autoformat" branch in the public repo?

**Comment by riccardobl** [comment]
nope, removed.

**Comment by stephengold** [comment]
This feature was disabled at 7c20f951 (12 October 2023).

**Pull request merged**
