### PR TITLE
Android native sound fix and update openal-soft to 1.21.1

### PR DESCRIPTION
**Pull request by joliver82**
This PR fixes issue https://github.com/jMonkeyEngine/jmonkeyengine/issues/1239 (both sound not working and ogg files not loaded).

Also this PR updates openal-soft to latest (1.21.1).

EDIT: I saw it's failing to compile. Maybe this is caused by an old release of the ndk, I'm using latest (22)

### CODE REVIEW

**Comment by Ali-RS** [comment]
Thanks, @joliver82 

What is bsinc_inc.h needed for?

**Comment by joliver82** [comment]
bsinc_inc.h is an autogenerated header file for openal-soft 1.19.1 (see commit https://github.com/joliver82/jmonkeyengine/commit/fc99412186fa3e43912a319d56542ff54b72686b) for 1.21.1 is useless and I've just removed it

**Comment by MeFisto94** [comment]
Well, you bumped the Target Version from 9 to 19, so that certainly requires a more recent NDK. 
It may be worth asking @riccardobl to update https://github.com/jMonkeyEngine/jmonkeyengine/blob/fc8128c139ac6cbde7a8a8db665bb4e1ca6ecbc9/.github/workflows/main.yml#L64 and it's integrated NDK version.

This is something that may even fix the compiler issues.
The "optimal" solution here would be to look at the relevant bytecode and find out why optimization fails, maybe with the help of some clang/gcc guys. Maybe we can make it more clear from the source code to prevent that issue, if it's not fixed in a more recent version already.

I mean the compiler shouldn't like change values into -1 randomly.
That may however be done after this workaround, but having Optimizations, especially on mobile devices, is a good idea

**Comment by joliver82** [comment]
Android api level 19 stands for kitkat 4.4 which was released on 2013 so I assume riccardobl's image is new enough to support it.

I agree that it would be better to properly fix this keeping optimizations enabled but I'm not that good at C/C++ and I didn't want to change code from external libraries (the issues are located at tremor and openal-soft)

About enabling C++14, if setting any -str=c++* flag ndk-build fails because there's plain C files (com_jme3_*.c) in the same library, that's why I didn't.

**Comment by Ali-RS** [comment]
>it would be great if @riccardobl could just rebuild the riccardoblb/buildenv-jme3:android docker image so we would use latest ndk to build jme3 android natives (and also add file package to avoid the ndk line 148 error)

I am not familiar with JME's build env but can this be configured from https://github.com/jMonkeyEngine/buildenv-jme3?

then changing this
https://github.com/jMonkeyEngine/jmonkeyengine/blob/fc8128c139ac6cbde7a8a8db665bb4e1ca6ecbc9/.github/workflows/main.yml#L64

to use `jmonkeyengine/buildenv-jme3`

**Comment by riccardobl** [comment]
> > it would be great if @riccardobl could just rebuild the riccardoblb/buildenv-jme3:android docker image so we would use latest ndk to build jme3 android natives (and also add file package to avoid the ndk line 148 error)
> 
> I am not familiar with JME's build env but can this be configured from https://github.com/jMonkeyEngine/buildenv-jme3?
> 
> And about this:
> 
> https://github.com/jMonkeyEngine/jmonkeyengine/blob/fc8128c139ac6cbde7a8a8db665bb4e1ca6ecbc9/.github/workflows/main.yml#L64
> 
> Should we change it to use `jmonkeyengine/buildenv-jme3:android`? (https://hub.docker.com/r/jmonkeyengine/buildenv-jme3)

Yes. It should be changed to `jmonkeyengine/buildenv-jme3:android` (from https://hub.docker.com/u/jmonkeyengine) . 
As you have noticed I mirrored my repo to the jme org, but i've never actually changed the references in the build script.

**Comment by joliver82** [comment]
I just changed it. The image was built 12 days ago, so it should have latest ndk and compile properly

**Comment by MeFisto94** [comment]
Well it is based on https://github.com/jMonkeyEngine/buildenv-jme3/blob/f6a80d1bf5ae39746b84b2391d9ebb28135b3168/android/Dockerfile, so it should be recent enough

**Comment by Ali-RS** [comment]
Note that `/opt/android/ndk-bundle/build/ndk-build: line 151: file: command not found` is still exist so.

**Comment by joliver82** [comment]
Not a real issue, but I'll add file package to the docker image later

**Comment by Ali-RS** [comment]
Thanks

**Comment by stephengold** [comment]
Is this PR ready to be integrated?

**Comment by joliver82** [comment]
> Note that `/opt/android/ndk-bundle/build/ndk-build: line 151: file: command not found` is still happening. In case this is still an issue!

Created a PR for buildenv to fix this



> Is this PR ready to be integrated?

From my point of view, it is

**Pull request merged**
