### PR TITLE
Add The Afflicted Forests to README.md

### PR DESCRIPTION
**Pull request by yaRnMcDonuts**
Not sure if this list is only for released games, or if a coming-soon title is allowed (feel free to deny this pr if not)

### CODE REVIEW

**Comment by stephengold** [comment]
The proposed link points to some interesting articles about the project.

I don't think there's a hard-and-fast policy for inclusion. We list Mythruna, but that at least has a test release available for download.
 
@yaRnMcDonuts What's the availability of The Afflicted Forests? Is there anything people can actually run?

**Comment by yaRnMcDonuts** [comment]
It is technically in beta on steam (although not publicly listed on the Steam store yet), and it can be tested by any Steam user who has a beta key. 

Although it has been over 2 years since I updated the steam version because I unfortunately had no one contact me for keys when I announced it in the past on my IndieDb and social media accounts for my game, and Steam's stats shows no activity amongst the people who were given keys, sadly (lots of people asked for keys then never even activated them, so that was also a bit discouraging).

I'm hoping to try another round of Beta testing soon, and can share keys with any JME user who is interested. But I admittedly have been discouraged from posting any recent updates to Steam since it started to feel like wasted time when no one was actually playing it, and I had a few times where I rushed to update it for a few people who asked for keys, only to find that they didn't actually try it or even activate their key.

So right now I'm trying to just improve my game visually and market it as much as possible in hopes of gathering more interest before I do another announcement about beta keys and start posting updates again.

**Comment by pspeed42** [comment]
Yeah, marketing is hard.  Mythruna has a dedicated core set of users and a ton of old momentum and I'm still lucky to get 4-5 downloads when I do a new release... and that's with a significant amount of weekly work that's almost entirely for organic marketing (weekly videos, weekly live stream, etc.)

**Comment by stephengold** [comment]
I support this pull request.

**Pull request merged**
