### PR TITLE
Remove print statements from FBX plugin

### PR DESCRIPTION
**Pull request by wyskoj**
This changes a print statement in `FbxAnimCurveNode.java` to a logger call so it doesn't contaminate output.

### CODE REVIEW

**Comment by stephengold** [comment]
Thank you for proposing this change.

The FBX loader contains 13 print statements directed to `System.out`. Why does this particular print statement cause an issue?

Does the issue relate to `FbxDump.dumpFile()` or is there some other impact?

**Comment by wyskoj** [comment]
I spent some time resolving warnings logged by JME in my project, and noticed I kept getting this print statement. So this was the only one that affected me, but if you prefer, I could do the same to the rest of the occurrences.

**Comment by wyskoj** [comment]
I know it's not a warning. In the process of resolving warnings, I spotted the output of this print statement in my console. And it doesn't help me to have it there (and frankly I'd like to have it gone). And by making it a `fine` call, it can still be seen—if wanted—by setting the logger level.

So, yes, that is the the only impact—just me being picky on the cleanliness of my console :)

**Comment by stephengold** [comment]
Thank you for your patience. Now that I understand the issue/motivation, I'm OK with this PR as is.

However, I notice that the straightforward conversion of `println()` to `Logger.fine()` results in some inefficient code: converting floats to strings, concatenating them, and then (in the usual case) not using the result. If you're agreeable, I suggest simply commenting out the original `println()`, similar to what was done in `FbxLoader.constructAnimations()`.

**Comment by wyskoj** [comment]
Yes, I do agree. An alternative would be to define the string lazily. But I don't suspect these statements are getting enough attention to warrant implementing that. I'll comment them out.

**Review by stephengold — APPROVED** [review]
Looks good. Thanks for your cooperation and thoroughness!

**Pull request merged**
