### PR TITLE
implement equals(), hashCode(), and isSimilar() for bounding volumes

### PR DESCRIPTION
**Pull request by stephengold**
This PR addresses the enhancements request in issue #2249.

Since the PR overrides `equals()`, it must also override `hashCode()` because the contract of `hashCode()` specifies that objects that are equal must return the same code.
 
The new methods intentionally ignore the `checkPlane` field, which holds auxiliary data used by the `Camera` class.

### CODE REVIEW

**Comment by stephengold** [comment]
@pspeed42: If you've got a moment, I'd like your opinion on whether `equals()` and `hashCode()` should ignore the `checkPlane` field or not.

**Comment by pspeed42** [comment]
It probably should ignore... but probably also that's up to the class that contains the field.  It would maybe be more forward-thinking of these subclasses called super.equals() and super.hashCode() as part of their processing rather than hoping to grab the right fields from the super class (which in my opinion should have been private fields in the first place... but that's a different religious hill to die on another day).
Also, was there a reason that Objects.hash() wasn't used vs hand-coding?

**Comment by stephengold** [comment]
Thanks for your insights, Paul.

**Comment by stephengold** [comment]
ready for review

**Pull request merged**
