### PR TITLE
GlfwMouseInput:  scale mouse coords only if Retina AppSetting is true

### PR DESCRIPTION
**Pull request by stephengold**
Proposed fix for #1745.

### CODE REVIEW

**Comment by stephengold** [comment]
The fix is somewhat tricky to test. Due to persistent settings and the recent change of default, it's possible to have the Retina flag set to `true` without knowing it. Also, the default LWJGL (in jme3-examples) is still LWJGL v2.

**Review by richardTingle — APPROVED** [review]
Looks good to me

**Comment by stephengold** [comment]
Thanks for your help @richardTingle and @bob0bob!

**Comment by bob0bob** [comment]
This fix works for me after getting rid of the "saved" settings,  because JME already set it to "true" by default and re-running brought them back, but when I erased the settings, it worked great.

**Comment by stephengold** [comment]
Thanks, @bob0bob. It looks like this PR will be superseded by #1753 though.

Also, it's integrated into both "master" and "v3.5", so it ought to be closed by now. I wonder why it isn't...

**Pull request merged**
