### PR TITLE
Remove jogl 

### PR DESCRIPTION
**Pull request by ItsMike54**
This PR removes support for JOGL from core lib as it is filled with bugs and developers using jME rarely use JOGL for rendering. LWJGL is rather built for games.

### CODE REVIEW

**Comment by tlf30** [comment]
I think this PR can close #1092 and #796

**Comment by ItsMike54** [comment]
> I think this PR can close #1092 and #796

Sounds good!

**Comment by stephengold** [comment]
At the moment, this PR seems very incomplete. It still needs to deal with `AppSetting`, `JmeDesktopSystem`, the build scripts, and the jme3-examples and jme3-jogl subprojects,

**Comment by ItsMike54** [comment]
@stephengold , is anything specifically missing still in the AppSettings and JmeDesktopSystem classes?
The latest commits have removed jogl references, and the build scripts also seem to have all references to the jme3-jogl project removed. 
As far as jme3-examples, I'll test the examples and make sure they are working fine.
And where are the jme3-jogl subprojects found at? This PR removes the jme3-jogl directory completely, so there is no longer anything inside it.

**Comment by stephengold** [comment]
Wtf?? It seems I cloned the wrong branch: your "ItsMike54-rm_jogl" branch instead of your "rm_jogl" branch. I regret the confusion my error caused.

However, there are still references to JOGL in Java comments:
 + com.jme3.opencl.package_info.java
 + AppSettings.java
 + TestApplet.java
 + HelloOpenCL.java
 + TestContextSwitching.java
 + TestOpenCLLibraries.java
 + TestVertexBufferSharing.java
 + TestWriteToTexture.java
 + TestMultiPostWater.java

Now seems the right time to remove those.

**Comment by ItsMike54** [comment]
Well that might confuse anybody. In meantime, I'll remove the references.

**Comment by tlf30** [comment]
@ItsMike54 both for the sanity of the ci system and my email, please group edits in as few as possible commits. 

It is fine to make a couple extra commits when you realize you forgot something, but there is no need to have a commit for each change. All it does is re-trigger the ci build, and email everyone on the pr. 

Thanks,
Trevor

**Comment by oxplay2** [comment]
10 people just receiving 10 emails:  :eyes: 

Please make single commits with multiple files Mike :)

**Comment by stephengold** [comment]
Looks good. Integrating...

**Comment by ItsMike54** [comment]
Lots of shit going on here

**Pull request merged**
