### PR TITLE
Updated Nifty to 1.4.3 and cleaned up the build

### LINKED ISSUE #981: Update Nifty GUI to 1.4.3
Update Nifty GUI to 1.4.3. Some minor fixes also discussed in jME forums and some possibly breaking API changes. Test and update.

https://github.com/nifty-gui/nifty-gui/releases/tag/nifty-main-1.4.3

### PR DESCRIPTION
**Pull request by tonihele**
Resolves #981 

The JME Nifty examples work. So does our project which uses Nifty quite heavily.

### CODE REVIEW

**Comment by stephengold** [comment]
I'm considering this PR for the JME 3.2.3 release.

Has this change had much testing with Linux? I ask because Toboi reported a crash running Maud v1.0.0-alpha.6 on Kubuntu. The stack trace made me think it might be related to Nifty 1.4.3, so I rolled back to 1.4.2 in my next release of Maud, and that seemed to resolve Toboi's issue.

https://hub.jmonkeyengine.org/t/seeking-alpha-testers-for-maud/39085/55

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 3896  org.lwjgl.opengl.GL15.nglBufferData(IJJIJ)V (0 bytes) @ 0x00007f41c8aa9c0e [0x00007f41c8aa9bc0+0x4e]
J 3953 C1 org.lwjgl.opengl.GL15.glBufferData(ILjava/nio/FloatBuffer;I)V (38 bytes) @ 0x00007f41c8adf584 [0x00007f41c8aded60+0x824]
J 3952 C1 com.jme3.renderer.lwjgl.LwjglGL.glBufferData(ILjava/nio/FloatBuffer;I)V (11 bytes) @ 0x00007f41c8ae03f4 [0x00007f41c8ae0340+0xb4]
J 3842 C1 com.jme3.renderer.opengl.GLRenderer.updateBufferData(Lcom/jme3/scene/VertexBuffer;)V (312 bytes) @ 0x00007f41c8a8f7ac [0x00007f41c8a8e780+0x102c]
J 3744 C1 com.jme3.renderer.opengl.GLRenderer.setVertexAttrib(Lcom/jme3/scene/VertexBuffer;Lcom/jme3/scene/VertexBuffer;)V (573 bytes) @ 0x00007f41c8a6e1f4 [0x00007f41c8a6d240+0xfb4]
J 3974 C1 com.jme3.renderer.opengl.GLRenderer.renderMeshDefault(Lcom/jme3/scene/Mesh;II[Lcom/jme3/scene/VertexBuffer;)V (242 bytes) @ 0x00007f41c8aec7a4 [0x00007f41c8aeb500+0x12a4]
j  com.jme3.renderer.opengl.GLRenderer.renderMesh(Lcom/jme3/scene/Mesh;II[Lcom/jme3/scene/VertexBuffer;)V+145
j  com.jme3.material.logic.DefaultTechniqueDefLogic.renderMeshFromGeometry(Lcom/jme3/renderer/Renderer;Lcom/jme3/scene/Geometry;)V+49
J 3967 C1 com.jme3.material.logic.DefaultTechniqueDefLogic.render(Lcom/jme3/renderer/RenderManager;Lcom/jme3/shader/Shader;Lcom/jme3/scene/Geometry;Lcom/jme3/light/LightList;I)V (21 bytes) @ 0x00007f41c8ae6dc4 [0x00007f41c8ae6c60+0x164]
J 4016 C1 com.jme3.material.Material.render(Lcom/jme3/scene/Geometry;Lcom/jme3/light/LightList;Lcom/jme3/renderer/RenderManager;)V (130 bytes) @ 0x00007f41c8b0972c [0x00007f41c8b08ee0+0x84c]
J 4028 C1 com.jme3.material.Material.render(Lcom/jme3/scene/Geometry;Lcom/jme3/renderer/RenderManager;)V (11 bytes) @ 0x00007f41c8b1808c [0x00007f41c8b17f00+0x18c]
j  com.jme3.font.BitmapText.render(Lcom/jme3/renderer/RenderManager;Lcom/jme3/math/ColorRGBA;)V+49
j  com.jme3.niftygui.RenderDeviceJme.renderFont(Lde/lessvoid/nifty/spi/render/RenderFont;Ljava/lang/String;IILde/lessvoid/nifty/tools/Color;FF)V+180
j  de.lessvoid.nifty.render.ScalingRenderDevice.renderFont(Lde/lessvoid/nifty/spi/render/RenderFont;Ljava/lang/String;IILde/lessvoid/nifty/tools/Color;FF)V+51
j  de.lessvoid.nifty.render.NiftyRenderEngineImpl.renderText(Ljava/lang/String;IIIILde/lessvoid/nifty/tools/Color;)V+98
j  de.lessvoid.nifty.elements.render.TextRenderer.renderLine(IILjava/lang/String;Lde/lessvoid/nifty/render/NiftyRenderEngine;II)V+13
j  de.lessvoid.nifty.elements.render.TextRenderer.renderLines(Lde/lessvoid/nifty/elements/Element;Lde/lessvoid/nifty/render/NiftyRenderEngine;[Ljava/lang/String;)V+222
j  de.lessvoid.nifty.elements.render.TextRenderer.render(Lde/lessvoid/nifty/elements/Element;Lde/lessvoid/nifty/render/NiftyRenderEngine;)V+15
J 3991 C1 de.lessvoid.nifty.elements.Element.render(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V (104 bytes) @ 0x00007f41c8afd6bc [0x00007f41c8afcaa0+0xc1c]
j  de.lessvoid.nifty.elements.Element.renderInternalChildElements(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V+27
j  de.lessvoid.nifty.elements.Element.renderChildren(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V+55
J 3991 C1 de.lessvoid.nifty.elements.Element.render(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V (104 bytes) @ 0x00007f41c8afd81c [0x00007f41c8afcaa0+0xd7c]
j  de.lessvoid.nifty.elements.Element.renderInternalChildElements(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V+27
j  de.lessvoid.nifty.elements.Element.renderChildren(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V+55
J 3991 C1 de.lessvoid.nifty.elements.Element.render(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V (104 bytes) @ 0x00007f41c8afe144 [0x00007f41c8afcaa0+0x16a4]
j  de.lessvoid.nifty.elements.Element.renderInternalChildElements(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V+27
j  de.lessvoid.nifty.elements.Element.renderChildren(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V+55
J 3991 C1 de.lessvoid.nifty.elements.Element.render(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V (104 bytes) @ 0x00007f41c8afe144 [0x00007f41c8afcaa0+0x16a4]
j  de.lessvoid.nifty.elements.Element.renderInternalChildElements(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V+27
j  de.lessvoid.nifty.elements.Element.renderChildren(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V+55
J 3991 C1 de.lessvoid.nifty.elements.Element.render(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V (104 bytes) @ 0x00007f41c8afe144 [0x00007f41c8afcaa0+0x16a4]
j  de.lessvoid.nifty.screen.Screen.renderLayers(Lde/lessvoid/nifty/render/NiftyRenderEngine;)V+31
j  de.lessvoid.nifty.Nifty.render(Z)V+46
j  com.jme3.niftygui.NiftyJmeDisplay.postQueue(Lcom/jme3/renderer/queue/RenderQueue;)V+20
j  com.jme3.renderer.RenderManager.renderViewPort(Lcom/jme3/renderer/ViewPort;F)V+423
```

**Comment by tonihele** [comment]
I dont remember did I test this on Windows or Linux. I do have both. And
with NVIDIA and Intel graphics.

Im currently billions of kilometers away from home. Okay, more than 10
000km. I could try this earliest on next Sunday.

I guess one way is looking Nifty GIT for changes somewhere in the files
listed in the stack. Or even 1.4.2 vs 1.4.3. I doubt there are lot given
the current development pace.

**Comment by stephengold** [comment]
Thanks for the reply. If you could test `jme3-nifty` on Linux with both adapters, that'd be great.

The JME 3.2.3 release is about 2 billion milliseconds away, so no rush.

**Comment by tonihele** [comment]
Works (Kubuntu 18.10):
INFO: Running on jMonkeyEngine 3.3-6683
 * Branch: master
 * Git Hash: 17e393e
 * Build Date: 2018-12-30
Mar 07, 2019 9:57:41 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 3.2.1 build 12 context running on thread main
 * Graphics Adapter: GLFW 3.3.0 X11 GLX EGL clock_gettime evdev shared
Mar 07, 2019 9:57:41 PM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: Intel Open Source Technology Center
 * Renderer: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) 
 * OpenGL Version: 4.5 (Core Profile) Mesa 18.2.2
 * GLSL Version: 4.50
 * Profile: Core

**Comment by tonihele** [comment]
Works (Kubuntu 18.10, LWJGL 2):
INFO: Running on jMonkeyEngine 3.3-6683
 * Branch: master
 * Git Hash: 17e393e
 * Build Date: 2018-12-30
Mar 07, 2019 10:07:50 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
Mar 07, 2019 10:07:50 PM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: Intel Open Source Technology Center
 * Renderer: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) 
 * OpenGL Version: 4.5 (Core Profile) Mesa 18.2.2
 * GLSL Version: 4.50
 * Profile: Core

**Comment by stephengold** [comment]
Thank you!

**Pull request merged**
