### PR TITLE
JmeSurfaceView: Removed explicit nullifying GlSurfaceView onDestroy

### PR DESCRIPTION
**Pull request by Scrappers-glitch**
This exception is an android native exception issue #1804 , raised due to trying to use the nullified object before being recycled : 
```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jme3.hellojmesurfaceview, PID: 12825
    java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
        at android.view.ViewGroup.addView(ViewGroup.java:4994)
        at android.view.ViewGroup.addView(ViewGroup.java:4976)
        at com.jme3.app.jmeSurfaceView.JmeSurfaceView.addGlSurfaceView(JmeSurfaceView.java:551)
        at com.jme3.app.jmeSurfaceView.JmeSurfaceView$RendererThread.run(JmeSurfaceView.java:207)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
 ```

### CODE REVIEW

**Comment by Scrappers-glitch** [comment]
I am currently testing this !

**Comment by Scrappers-glitch** [comment]
The problem is fixed by removing this line !

**Comment by pspeed42** [comment]
Who was the crazy guy who added that anyway?!? :) :) :)

https://github.com/jMonkeyEngine/jmonkeyengine/pull/1650

**Comment by Scrappers-glitch** [comment]
> Who was the crazy guy who added that anyway?!? :) :) :)
> 
> #1650

I agree this was crazy, but you will never believe me, if i told that it was working like a charm on android 10, and on android 11, it sometimes works, but most of time it shows this exception, the problem lies within `setRequestOrientation()` which destroys and recreate the activity !!

**Comment by Scrappers-glitch** [comment]
I added the code that removes and destroys android views to prevent GlSurfaceViews overlapping.

**Comment by stephengold** [comment]
We all make mistakes. I, for one, appreciate software contributors who hang around and help maintain their contributions.

Not being an Android developer, I don't feel qualified to review this PR. If there's no substantive discussion, I'll integrate it.

**Comment by Scrappers-glitch** [comment]
@stephengold i just noticed that i wasn't following the package naming conventions on `com.jme3.app.jmeSurfaceView;`, it should be `com.jme3.app.view;` instead ! Do i need to  rename it in another PR ? (AFAIK, i haven't seen anyone yet using jmesurfaceview, let me know what you think).

**Comment by stephengold** [comment]
Someone mentioned the package naming issue to me---I forget who. It's the sort of issue that's easy to solve before a library is released, but difficult to solve afterward. To fix it now, I believe we'd either have to duplicate source code in the "jme3-android" library or else break existing apps. That being the case, I don't think it's worth fixing. Instead, we'll learn from the mistake and carry on.

If we wanted to strictly conform to Java's package naming conventions, we'd either have to move all our packages out of "com.jme3" or else acquire the "jme3.com" domain from Jack M. Estes III.

**Comment by Scrappers-glitch** [comment]
I think we have the forums if existing apps break, one could ask what had happened, and the release notes is a direct guide of engine changes.

**Comment by pspeed42** [comment]
"com.jme3" issues aside since that's a completely different topic...

How many releases did "com.jme3.app.jmeSurfaceView" go into?  Is this normally something that a user codes to directly or is it normally hidden?

**Comment by Scrappers-glitch** [comment]
> "com.jme3" issues aside since that's a completely different topic...
> 
> How many releases did "com.jme3.app.jmeSurfaceView" go into? Is this normally something that a user codes to directly or is it normally hidden?

The feature is added since jme-3.4.

**Comment by Scrappers-glitch** [comment]
Okay, i have looked up the android core packages, i found the major package `android.view` where android views live and `android.app` where android application components live, but special featured android views are located within special packages like `android.webkit.WebView` and `android.opengl.GlSurfaceView`, so i think the best packaging option out there for JmeSurfaceView is `com.jme3.view.surfaceview.JmeSurfaceView` and i will create a `package-info` for it, if you are okay with these changes or have an objection let me know.

`com.jme3.view` can hold other android views as features for jme.

**Comment by Scrappers-glitch** [comment]
Further discussion on : #1803

**Comment by Scrappers-glitch** [comment]
@stephengold Could you please link this PR to this issue #1804, thank you.

**Comment by capdevon** [comment]
> Someone mentioned the package naming issue to me---I forget who

It was me on Nov 21, 2021 in a private message :) Honestly I'd be more inclined to correct the error and rename the package as Pavl suggested. The functionalities are the same and it takes very little to recompile an application. We all make mistakes, but this should be solved because a good programmer seeing such a thing would think that the whole engine is of low quality and would not use it. I appreciate Pavl's contribution and support on Android and I don't condemn his mistake, but the quality of an engine can also be seen in the details. A description of the change in the release notes of the next version will easily help programmers understand what to do to recompile their application if they have used the class.

**Comment by capdevon** [comment]
There is a typo on xmL. The capital 'L' and lowercase 'xm'.
```java
/**
 * <b>A RelativeLayout class holder that holds a {@link GLSurfaceView} as a renderer UI component and uses {@link OGLESContext} as a renderer context to render
 * a jme game on an android view for custom xmL designs.</b>
 * ...
 */
```

https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/JmeSurfaceView.java#L70

**Comment by Scrappers-glitch** [comment]
@capdevon thank you.

**Comment by Scrappers-glitch** [comment]
I have nothing to add on this PR, @capdevon 's notes are taken down for the time of documentation improvements.

**Comment by stephengold** [comment]
@Scrappers-glitch: with your permission, I'd like to make @capdevon's suggested change and then integrate this PR into jMonkeyEngine:master.

**Comment by Scrappers-glitch** [comment]
> @Scrappers-glitch: with your permission, I'd like to make @capdevon's suggested change and then integrate this PR into jMonkeyEngine:master.

I was planning to do that on another documentation PR before package changes. Would that be more appropriate ?

**Comment by stephengold** [comment]
@Scrappers-glitch Since the typo isn't related to this PR, that will be fine.

**Pull request merged**
