### PR TITLE
setUserObject called when cloning controls - bug fixed (issue #797)

### PR DESCRIPTION
**Pull request by thoced**
Hi, 
I think I corrected this problem, can you see if this is correct ?
 When testing with RigidBodyControl, the null value was placed in the setUserObject. The spatial (in the case of RigidBodyControl), was not copied.

Thanks

### CODE REVIEW

**Comment by Nehon** [comment]
@pspeed42 what do you think of this fix? 
related to https://github.com/jMonkeyEngine/jmonkeyengine/issues/797

**Comment by pspeed42** [comment]
Is it weird that the object isn't cloned?  I feel like the usage implies that the default behavior should be to use JME cloner to clone the object in the cloneFields() method.

From the usage, it looks like the fix really should have been in cloneFields() to use the cloner to clone the user object (which would have reused the spatial if it was the spatial).  Of course, since the super.clone() method is not called you probably still need to copy the reference as is done in this patch but I think this is only a partial solution.

**Comment by pspeed42** [comment]
Why are we calling setUserObject()?  I think I lost the bubble on that one.

...I think it's an odd side-effect that setUserObject() will be called for clones.

**Comment by stephengold** [comment]
I don't believe this is the right fix for the issue. I'd like to close this PR without integrating it.

**Pull request closed without merging**
