### PR TITLE
Migrate TestSkeletonControlRefresh to new anim system

### PR DESCRIPTION
**Pull request by syluna**
Migrate SkeletonControl to new SkinningControl

### CODE REVIEW

**Comment by syluna** [comment]
Ok realy stange... I close the other branch and recreate it and populate with one commit.
I push other migrated test and it works. Why this test failure on low level check...(sometime linux, mac)

**Comment by Ali-RS** [comment]
This failure has nothing to do with your PR I guess. 
Seems it's due to `Unable to connect to azure.archive.ubuntu.com:http`

**Comment by MeFisto94** [comment]
No need to re-open PRs, I just re-started the build. It seems that Github Actions has Internet problems from time to time.

But when it passes on one platform, others are okay as well (because it's about the java code and not the natives)

**Comment by stephengold** [comment]
It appears you reformatted and removed trailing whitespace. This makes it difficult to review the PR. Please limit your PRs to just the necessary changes.

**Comment by pspeed42** [comment]
Except in this case there were a lot of funky 3 space indents.  I'm ok with fixing those especially since these test changes are near-rewrites anyway.

At least there aren't any hard tabs in this one.

**Comment by syluna** [comment]
Sorry, I reconfigure my IDE to disable auto formate...

**Comment by stephengold** [comment]
I'm not okay with this as it stands. There still sections of code that were reformatted without being rewritten. While I generally support reformatting, it should be in a separate PR, not mixed in with other changes.

**Comment by pspeed42** [comment]
Of the 160 changes, about 30 of the lines were formatting changes.  Only about half of which were in unrelated sections.

But I guess if we want him to put back the three space indents then that's fine.

**Comment by syluna** [comment]
I take note of it for my possible next participation. I just wanted to help and do well. Sorry.

**Comment by stephengold** [comment]
Looks better now. Thank you!

**Comment by stephengold** [comment]
Can you eliminate the inner class?

**Comment by syluna** [comment]
Sure, done.

**Comment by stephengold** [comment]
I think this is ready to be integrated.

**Pull request merged**
