### PR TITLE
Jme3 vr dev

### PR DESCRIPTION
**Pull request by jseinturier**
I propose a new JMonkey module dedicated to Virtual Reality rendering (VR). This integration is a fork of the original phr00t [JMonkeyVR ](https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=0ahUKEwjp2vTF_9_RAhXLiRoKHRCBDD0QFggaMAA&url=https%3A%2F%2Fgithub.com%2Fphr00t%2FjMonkeyVR&usg=AFQjCNHQ167Xu07HfX0HPcIvFeMdaVwnRA&sig2=-ArPTml-l9fhIyX2M60-3Q&bvm=bv.145063293,d.ZGg) library that was built on a customized version of JMonkey.

I've modified the VR specific module in order to make it integrate with official JMonkey release (and without refactoring any JMonkey core content).

This VR module relies on either OpenVR or OSVR underlying system. It enables to make VR rendering on various devices (HTC vive, PlaystationVR, ...) using one of the previousle cited API.

I've tested and i'm using this module to produce VR demos.

If i can access the JMonkey wiki, i will provide a simple tutorial for using VR capabilities within JMonkey environment. I've not included any example within the actual module as i want to minimize its dependencies (actually only jme3-core, jme3-effects and jme3-lwjgl3).

I hope that this work will interest you.

### CODE REVIEW

**Comment by neph1** [comment]
I'll try this out (hopefully) in a couple of weeks.

**Comment by jseinturier** [comment]
I've finished the integration of OpenVR 1.0.6. I know that many project aims at providing OpenVR binds for java (even LWJGL 3.1.2 provide now an OpenVR integration). I've made the choice to produce my own java bindings in order to follow the openVR / JME releases as soon as possible.

**Comment by Nehon** [comment]
so... 237 files to review 🥇 
I'm a bit too busy (lazy) to review all of them, so could you answer those questions please? 
1. Does this pr modify the core (as in any other jme-xxx module)? Seems your initial approach was to avoid that, and that's great, but did you achieve it?
2. What's the used approach? Are you still extending SimpleApplication as phroot did? or is it entirely AppState based? (I could at least check this one out myself though, but hint: option 2 is way better)
3. Does it use instancing as phroot did? Seems to be the standard of the industry now.
4. You said playstationVR?
5. I have no fifth question but it's to check if you read all my questions?

hint: 5th question is a trap.

Thanks for the hard work. ;)

**Comment by jseinturier** [comment]
Hello Nehon. Here is the answers to your questions:

_1. Does this pr modify the core (as in any other jme-xxx module)? Seems your initial approach was to avoid that, and that's great, but did you achieve it?_
**NO** my jme3-vr module **DOES NOT** require **ANY** modification of the core distribution. The main goal of this fork from phr00t previous work was to deal with the original JMonkey distribution without any modification. The commited sources of jme-vr does not modify any core sources.
More over, the two aims of the jme3-vr module are:
1. To use the original JMonkey distribution
2. To conform to Java best practices (the phr00t distribution relies onmethod and classes that are linked using static methods and field and it is so difficult to modularize the components).
3. To easy the following of the underlying VR systems (OpenVR, OSVR, ...) and to keep the jme3-vr module up to date.
4. To minimize the external dependencies (at this time only JNA library is needed out the other JMonkey module).
The current commit validate the 4 points above.

_2. What's the used approach? Are you still extending SimpleApplication as phroot did? or is it entirely AppState based? (I could at least check this one out myself though, but hint: option 2 is way better)_
The used approach is to extends SimpleApplication. As phr00t done, using only AppState is difficult as i need at this time many access to differents modules that are handled by the application itself.

_3. Does it use instancing as phroot did? Seems to be the standard of the industry now._
Yes the jme3-vr module can be used with instanced rendering. However, as the core shaders are not dedicated to instanced rendering, i've provided specific shaders that we have to use if we want to use instanced rendering. It is so not possible to switch between instanced / normal mode at runtime at this time.

_4. You said playstationVR?_
Yes, i aims to be compatible with playstationVR (via the old Morpheus project) but this integration relies on a hack of the morpheus project (https://www.reddit.com/r/PSVRHack/comments/58ylma/psvr_apimorpheus_bridge_on_github/) and at this time i've not worked on it.

_5. I have no fifth question but it's to check if you read all my questions?_
I think i've read all of your questions !!

_6. And you ?_
Have you read all my responses ?

Thanks for your interest !

**Comment by neph1** [comment]
(I believe) my fork of jMonkeyVR had full functionality of the application using an AppState, so it should be doable, but requires a bit of refactoring and trickery. I can redo the stuff with your fork, but I need some more time.

**Comment by Nehon** [comment]
cool cool.
Yes I've eagerly read all your answers.

Nice work!

**Comment by empirephoenix** [comment]
In my opinion this is mergable, however I would really like to see such  an appstate added later on, as this would enable almost all jme games to support VR. Many of the more complex games do not use necessarly a SimpleApplication compatible livecycle, and would have a lot of work to switch to this right now.

**Comment by empirephoenix** [comment]
Btw. since I did not immediately spot it, is there a helloVrTest or similar example included in this?

**Comment by neph1** [comment]
"Many of the more complex games do not use necessarly a SimpleApplication compatible livecycle, and would have a lot of work to switch to this right now."
This is a good argument. I initially had the idea that the main benefit of having an AppState would be runtime switches between VR and non-VR. Looking at other VR enabled games (on Steam at least), however, they are usually started in either mode and changing is not possible while the game is running.

**Comment by jseinturier** [comment]
I'm aware that you would have AppState dedicated to VR instead of an application, but i think that the main argument of switching from VR to traditional rendering for a same application is not so easy. Switching from desktop to VR is not only a question of rendering, many aspects of the application will differ: the controllers, the GUI, the observer, ... So for me, to add the capability to Jmonkey to switch at runtime between VR mode or Desktop mode is not relevant as it involves a lot of work and as i'm not sure that is a good approach to to develop an application that can handle VR and desktop (the complexity of the application could be very high). As 

More over, i've a deadline on March to produce a VR demonstrator based on JMonkey, so i'm not sure to have the time to refactor my code in order to use AppState, but it couldbe possible...

To empirephoenix, i've posted a sample application in this thread: [https://hub.jmonkeyengine.org/t/official-vr-module/37830/10]. I've not integrated the sample within jme3-vr as it requires dependencies that are not needed by the module (for example jme3-plugins for data loading).

**Comment by neph1** [comment]
Note: If it wasn't apparent in my comment, I don't think a runtime switch between VR/non-VR is something to strive for. It was just my initial motivation for the AppState.

**Comment by jseinturier** [comment]
Ok Neph1. I've just dowloaded your AppState and i'm working on an integration within jme3-vr, it should be done by next monday ;-)

**Comment by empirephoenix** [comment]
It might be any idea to put it into the examples project in jme3, as that has quite some dependencies anyway to other parts

**Comment by neph1** [comment]
OK. I thought I could do it in a while, but be my guest! If I remember correctly, the important bit is that the appstate (at least in the case of jMonkeyVR) had to be added before starting the application. Ref TestOpenVR .java : TestOpenVR test = new TestOpenVR(vrAppState);

**Comment by jseinturier** [comment]
Hello all,

It has been a lot ow work but i've committed the last version of jme-vr. The module now provide an app state (called VRAppState) that enable to use underlying VR system (at this time OpenVR and OSVR). The is no more need of a specific VR Application. 

You can get a sample within the forum (see the last post) at [https://hub.jmonkeyengine.org/t/official-vr-module/37830/15](https://hub.jmonkeyengine.org/t/official-vr-module/37830/15)**

**Comment by empirephoenix** [comment]
Hi, there still seems to be a minor issue with the build, did you do a recent merge with master? Apparently some method in the Shadow stuff was changed.

**Comment by jseinturier** [comment]
Hello, How can i merge from the master branch within my own one ?

**Comment by jseinturier** [comment]
Its ok, i've merged my branch with the master one and there is no more error.

I've just a question, i see that my JMonkey engine fork does not integrate later master commits. Is there a way within GitHub to synchronize my fork with the JMonkey official depot ?

**Comment by empirephoenix** [comment]
In .git/config add 
[remote "upstream"]
	url = https://github.com/jMonkeyEngine/jmonkeyengine.git
	fetch = +refs/heads/*:refs/remotes/upstream/*

then you can
"git pull upstream master" to get all new changes in upstream (assuming you are already in master of your copy)

**Comment by empirephoenix** [comment]
Thanks :)

**Comment by Nehon** [comment]
@jseinturier ... ok just noticed something in the core done by this PR.
https://github.com/jMonkeyEngine/jmonkeyengine/pull/607/files#diff-730c034af98a55411581659f9891ebeeR173

This is pretty bad.
Not only it's useless to have an additional method call for a bitwise operations, It gives access to the refresh flags of Spatial from this outside which is utterly bad.
refreshflags are internal to spatial and should not be directly changed from the outside.
Making them protected would have saved the thing, but here again we get to argument 1, it's useless.

I'm pretty pissed off to be honest because you specifically answered this : 

> 1. Does this pr modify the core (as in any other jme-xxx module)? Seems your initial approach was to 
avoid that, and that's great, but did you achieve it?
NO my jme3-vr module DOES NOT require ANY modification of the core distribution.

There is nothing more core than Spatial.java. It's the corner stone of JME. I would have liked that you mentioned this when I asked.

**Comment by jseinturier** [comment]
Hello,

I'm very sorry that my modified Spatial class has been embedded within a mergin attempt into the master repository. This modification was only for internal debug purpose (i needed to know where the flags of a spatial was modified when i was debugging instance  rendering).

I know that Spatial is THE core class of JME and i can confirm that jme-vr does not modify any core class (for now it does not modify any class outside the jmevr package).

With my late commit, you can see that there is no more modification of the Spatial class. I'm also thinking that there is no more modification of any JMonkey core class.

**Comment by Nehon** [comment]
> With my late commit, you can see that there is no more modification of the Spatial class. I'm also thinking that there is no more modification of any JMonkey core class.

Not sure what you mean by this, the change was effective on master. I reverted it yesterday https://github.com/jMonkeyEngine/jmonkeyengine/commit/d20cf3f20aa3a144b50448a4d88dfebe1f64b94e
Fortunately it seems you never call the public flags methods in the rest of the code, so the change shouldn't have break anything in jme-vr.

**Comment by jseinturier** [comment]
I wanted to say that i've used the modified Spatial on the early stage of my jme-vr development. I've no more used this class since. I've just missed the fact that the class was embedded within my pull request...

For now, i'm not modifying any class outside the jmr-vr packages.

**Comment by jseinturier** [comment]
I've a question. My computer was down for several week and i would like to restart working on jme-vr for now.

I've dowloaded the jme-vr fork and i've merged it with the latest master revision but when i run gradlew.bat i've got the following error:

Full Version: 3.2-6220
POM Version: 3.2.0-SNAPSHOT

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\jse\dev\java\jmonkey\git\jmonkeyengine\jme3-bullet-native\build.gradle' line: 26

* What went wrong:
A problem occurred configuring project ':jme3-bullet-native'.
> Exception thrown while executing model rule: bulletjme(org.gradle.nativeplatform.NativeLibrarySpec) { ... } @ jme3-bullet-native\build.gradle line 17, column 9
   > build_caiybjvuz2wy1t4x2oeln1cse$_run_closure2$_closure9$_closure12$_closure13$_closure14

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.094 secs

**Comment by empirephoenix** [comment]
usually that issue happens with wrong gradle version, but gradlew should ensure correct one. Test if changing the properties in gradle folder were version is does help

**Comment by jseinturier** [comment]
Thanks for the answer.

If i force Gradle version to 3.5 (within the eclipse IDE with buildship plugin), the project can be compiled without any problem. I'm looking forward with the gradlew script within the distrib.

**Comment by jseinturier** [comment]
If i modify the _gradle-wrapper.properties_ within the _gradle/wrapper_ directory by replacing:

distributionUrl=https\://services.gradle.org/distributions/gradle-3.2.1-bin.zip
by
distributionUrl=https\://services.gradle.org/distributions/gradle-3.5-bin.zip

the gradlew script within the distrib works fine. Maybe this modification should be done within the JME master ?

**Pull request merged**
