### PR TITLE
fixed the problem with saving/loading light probes.

### PR DESCRIPTION
**Pull request by JavaSaBr**
Fixed the problem with saving/loading light probes.

### CODE REVIEW

**Comment by JavaSaBr** [comment]
@Nehon could you look at this, please?

**Comment by pspeed42** [comment]
Note: we see all of the commits as they come through.  You don't have to mention us all the time unless it's been a while without comment.

**Comment by JavaSaBr** [comment]
ok :)

**Comment by Nehon** [comment]
mhh ("position", this)... that was dumb...

**Comment by Nehon** [comment]
Also @JavaSaBr you can just assign me in the "Reviewers" section on the top right I'll be notified.

I'll merge this PR once the build is green

**Comment by JavaSaBr** [comment]
@Nehon oh, ok :)

**Pull request merged**
