### PR TITLE
Migrate TestOgreAnim to new anim system

### PR DESCRIPTION
**Pull request by syluna**
I applied some changes to have the same rendering as the original test (Add static inner class LoopAction)

### CODE REVIEW

**Comment by stephengold** [comment]
Reformatting the code makes this PR difficult to review. Please limit your PRs to just the necessary changes.

**Comment by syluna** [comment]
Sorry, I'll be careful next time

**Comment by stephengold** [comment]
As it stands, you've changed the indentation from 4 spaces to 8 spaces. Please undo that also.

**Comment by stephengold** [comment]
Also, you re-ordered the methods. Please move `onAction()` back to the bottom of the file where it was before.

**Comment by pspeed42** [comment]
Looks like onAction() is at the bottom of the file.  There is an inner class below it now.

**Comment by stephengold** [comment]
Given the inner class, the new arrangement is reasonable.

**Comment by syluna** [comment]
Yes the inner class is only to keep the same result like old test (no loop anim). I can't find any way to do this.

**Comment by stephengold** [comment]
You're not the first person to be puzzled by this:
    https://hub.jmonkeyengine.org/t/solved-when-animcomposer-reaches-the-end-of-an-action/41652

**Comment by syluna** [comment]
Oh yes :) I didn't think about the Tweens sequence and callMethod ! Thanks Stephen

**Comment by stephengold** [comment]
In order to commit to integrating a PR, I'd need to see the PR. However, your proposal sounds promising, and I don't foresee any objections.

**Pull request merged**
