### PR TITLE
Update license headers in jme3-core

### PR DESCRIPTION
**Pull request by ItsMike54**
Most files in the engine have headers that only extend the copyright through 2012. This PR updates those files in jme3-core which haven't yet been updated.
2009-2020

### CODE REVIEW

**Comment by pspeed42** [comment]
The date range should only change if new updates were made to the file in question.  It's not right to just arbitrarily update the last date on all files.

**Comment by ItsMike54** [comment]
As in this PR is not needed? 
Also I'm curious as to why that isn't right.

**Comment by pspeed42** [comment]
As in this PR isn't needed.

The date range on a copyright means something.  You've decided that the end date doesn't mean anything.  Might as well leave it off then.

A file that hasn't been updated since 2012 does suddenly get to claim an extra 8 years of copyright protection just because we decide that it does.

**Comment by ItsMike54** [comment]
Fine then.

**Pull request closed without merging**
