### PR TITLE
Fixed some problems with getting an address of an LWJGL buffer.

### PR DESCRIPTION
**Pull request by JavaSaBr**
Fixed some problems with getting an address of an LWJGL buffer.

### CODE REVIEW

**Comment by JavaSaBr** [comment]
@empirephoenix any questions?

**Comment by empirephoenix** [comment]
Yes, :) What is the reason, that the memoryutils cannot be used? Do it cause errors when not having a bytebuffer but a flaotbuffer for example?

**Comment by JavaSaBr** [comment]
The main change is to get an address using position '0' of a buffer because the method to get an address returns different addresses for different positions for the same buffer. Also, I don't want to use direct cast from Buffer to ByteBuffer, so I just added instanceof checks.

**Comment by empirephoenix** [comment]
Oh i see, it did return the native pointer to the current position O.o yeah a wonder that did not crash instantly XD

**Pull request merged**
