### PR TITLE
fix mixed up javadoc description of euler angles

### PR DESCRIPTION
**Pull request by AlrikG**
I've noticed that the javadoc of the euler angle methods was incorrect and confusing, so I created this PR

- remove confusing description to fromAngles()
- fix incorrect description of toAngles()
- fix typo rall => roll

### CODE REVIEW

**Comment by empirephoenix** [comment]
This makes sense to me, and would explain some confusion I had years back with this methods :) Fine from my point of view.

**Comment by AlrikG** [comment]
I just realized there is something more messed up with that euler methods.
I have tested with this simple example. If I put something into roll and read it back, then pitch and yaw are also modified.

```
float pitch = 0;
		float yaw = 0;
		float roll = FastMath.PI;

		System.out.println("==============INPUT==============");
		System.out.println("pitch " + pitch);
		System.out.println("yaw " + yaw);
		System.out.println("roll " + roll);

		Quaternion q = new Quaternion();
		q.fromAngles(pitch, yaw, roll); // (pitch, yaw, roll)
		float[] angles = q.toAngles(null); // (yaw, roll, pitch) => (pitch, yaw, roll)

		System.out.println("==============OUTPUT jME javadoc - wrong order==============");
		System.out.println("pitch " + angles[2]);
		System.out.println("yaw " + angles[0]);
		System.out.println("roll " + angles[1]);

		System.out.println("==============OUTPUT same order as input======");
		System.out.println("pitch " + angles[0]);
		System.out.println("yaw " + angles[1]);
		System.out.println("roll " + angles[2]);
```

**Comment by empirephoenix** [comment]
Isn't that pi? 2pi is one rotation if im not wrong, so -pi == +pi or? The rest is artifacts from the conversions with floats

**Comment by AlrikG** [comment]
yes but why is pitch and yaw rotated by -pi and roll is 0? Should not roll == pi and pitch==yaw==0 ?

**Comment by pspeed42** [comment]
Euler angles are ambiguous.  A quaternion is not.  It is a compact representation of angles.  You are never guaranteed to get the same euler angles out that you put into it.  It's pure coincidence if you do.

**Comment by pspeed42** [comment]
You've removed the description on the order that the angles are applied.  That's important because it's completely arbitrary and makes a big difference.  If you apply them in a different order then you get different results.  I mean, it was wrong but it's important. :)  Order is yaw then pitch then roll.  I think the person writing the docs got confused with the difference between them.  yaw = rotation around y.  pitch = rotation around x.  roll = rotation around z.

**Comment by AlrikG** [comment]
OK then I will update the PR.

**Comment by AlrikG** [comment]
is it fine now?

**Comment by pspeed42** [comment]
The old text was wrong, I think.  We apply them in yaw, pitch, roll order.

**Comment by AlrikG** [comment]
hm if I get the source code right, the order in which the angles are applied is (z,y,x) aka (roll,yaw,pitch). Do you agree with me?

**Comment by pspeed42** [comment]
No, that's absolutely not the case.  Yaw is definitely first.  You look left/right before any other rotations are applied... otherwise you would induce side-effect roll with every other action.  (Imagine if you pitch first and then yaw, you will be inducing a roll as well.)

**Comment by pspeed42** [comment]
Reread your post... it is possible that roll is first but it would be very strange.  Probably we should write a test that uses something like a fly camera but with the mouse wheel used to add roll.  Then we'd see for sure.

**Comment by AlrikG** [comment]
ok then I build a test case if I have some time

**Comment by pspeed42** [comment]
Note: if you have the time... it might easier to add mouse wheel to roll support to the Lemur Gem for camera movement since it already keeps separate yaw/pitch instead of applying quaternions every time.

**Comment by empirephoenix** [comment]
dead

**Comment by AlrikG** [comment]
Sorry but its not dead. I didn't had time for it because of planning my wedding, personal projects, and so on. But I definitely will work on this PR as soon as I have some time.

**Pull request closed without merging**
