### PR TITLE
Jme3 vr dev

### PR DESCRIPTION
**Pull request by jseinturier**
Here are some changes to jme3-vr:

1. Updated OpenVR implementation to 1.0.9
2. User can specify external OpenVR library to load with openvr.library.path system property.
    Usage: java -Dopenvr.library.name=my_path_to_library MyApp
3. Removed reference to OCCULUS VR and OpenVR from VRAppstate as this class is generic and does not have to be linked to specific implementation.
4. VRMouseManager could be buggous using OSVR or Occulus VR. 
5. Refactored VR implementation packages in order to separate all available implementation. Modifying or adding implementation should no more impact other ones. 
6. Renamed VR implementation related classes in order to be uniform

### CODE REVIEW

**Comment by Nehon** [comment]
Tgis branch is weird you might want to rebase it with master

**Comment by jseinturier** [comment]
Done ;-)

**Comment by Nehon** [comment]
Still not good, the branch cannot be rebased
I guess the pb was that master was push forced at some point and you can't properly rebase.
you'd need to create another branch on current master and cherry pick your commits on it and make another PR

**Comment by jseinturier** [comment]
Hello,

I've done a refbase and updates with the current master branch and i don't get any conflict or problem... Do you want me to make another PR anymore ?

**Comment by Nehon** [comment]
no you did a merge apparently

**Comment by jseinturier** [comment]
Yes i've made a merge in order to check that all was ok... and all seems to be ok ;-)

**Comment by Nehon** [comment]
Well... look at the PR : 19 commits -> you actually made 2 useful commits.
also there is a big hint from github -> 
> This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

**Comment by jseinturier** [comment]
I'm sorry Nehon but i'm lost at this time... I'm seeing that my pull request contains commits from other developpers and i don't know why. Maybe i've done bad refbase at some time... But when i perform merge check on the PR, Github said that the jme3-vr branch can be merged within master branch automatically.

How can i solve the problems ? Do i have to restart from scratch my project ?

**Comment by Nehon** [comment]
It can be merged but not rebased. And I'd like to rebase it.
So basically your best choice now is to create another branch from master.
then cherry pick your commits. and IMO only this one is needed https://github.com/jMonkeyEngine/jmonkeyengine/pull/767/commits/8d3002bc1e0be1620b44e1d98302cd38a5a037ec

so basically on your fork do:
//go to master
git checkout master
//make sure master is up to date
git pull
//create branch and check it out
git checkout -b myNewBranch
//cherry pick the commit
git cherry-pick 8d3002b
//push on the remote
git push --set-upstream origin myNewBranch

Then make a PR from this branch

**Comment by Nehon** [comment]
The other one has been merged

**Pull request closed without merging**
