### PR TITLE
AppStateManager profiler for render and post render

### PR DESCRIPTION
**Pull request by tlf30**
Added profile tracking to AppStateManager for render and post render.

If the community thinks this is useful, feel free to merge, otherwise just close. I found it very helpful when tracing which app state was impacting my fps.

### CODE REVIEW

**Comment by pspeed42** [comment]
I don't object to it... but it's interesting that of the thousands of app states that I've written in various apps, maybe half a dozen do anything significant on render() or postRender().

**Comment by tlf30** [comment]
Yeah, this came up when troubleshooting Minie's BulletAppState which does blocking on render or post render depending if running in sequential or parallel. I would have never figured out it was bullet without this.

**Comment by stephengold** [comment]
I'm okay with this. Ready for integration.

**Comment by tlf30** [comment]
It is ready to merge when ever you are.

**Review by danielperano — APPROVED** [review]

**Pull request merged**
