### PR TITLE
fixed the NPE with controls

### PR DESCRIPTION
**Pull request by JavaSaBr**
If you can't load some control, you have a message about this, but in next iteration of render, you get crash with NPE.

### CODE REVIEW

**Comment by empirephoenix** [comment]
Shouldn't this be fixed in the loader instead?

**Comment by JavaSaBr** [comment]
I didn't find better place :)

**Comment by empirephoenix** [comment]
Hm after revisiting this, I kinda agree, could you add a warning that shows if it skips a null?

**Comment by JavaSaBr** [comment]
I have added it.

**Pull request merged**
