### PR TITLE
 Cleanup NativeLibraryLoader & fix wrong library path 

### PR DESCRIPTION
**Pull request by Ali-RS**
Solves  #1965

### CODE REVIEW

**Comment by Ali-RS** [comment]
For better review, I have made the changes in two commits :)

[Cleanup NativeLibraryLoader](https://github.com/jMonkeyEngine/jmonkeyengine/pull/1967/commits/6865822893071d5eca6b98497e30b5e90fd07f2b)

[Fix wrong library path](https://github.com/jMonkeyEngine/jmonkeyengine/pull/1967/commits/56bd09c67993d9f9684ccdc5a7b8e41f774531b9)

**Comment by Ali-RS** [comment]
Unless there's something to discuss, I plan to self-integrate this PR in about 24 hours.

**Comment by Ali-RS** [comment]
Should I apply this to the v3.6 branch?

**Comment by stephengold** [comment]
> Should I apply this to the v3.6 branch?

I'm not sure. Did #1965 ever cause correct applications to fail? If not, then this change seems like a big risk, especially if it hasn't been thoroughly tested on all platforms.

**Comment by Ali-RS** [comment]
I see, thanks for the comment

>Did https://github.com/jMonkeyEngine/jmonkeyengine/issues/1965 ever cause correct applications to fail?

I believe not.

**Comment by stephengold** [comment]
From my point of view, cherry-picking is all about risk versus benefit.

**Pull request merged**
