### PR TITLE
OpenVR 1.0.9 and Occulus Support

### PR DESCRIPTION
**Pull request by jseinturier**
User can specify external OpenVR library to load with
openvr.library.path system property.
Usage: java -Dopenvr.library.name=my_path_to_library MyApp

Removed reference to OCCULUS VR and OpenVR from VRAppstate as this class
is generic and does not have to be linked to specific implementation.

VRMouseManager can be buggous using OSVR or Occulus VR. 

Refactored VR implementation packages in order to separate all available
implementation. Modifying or adding implementation should no more impact
other ones. 

Renamed some classes in order to be uniform

### CODE REVIEW

**Comment by jseinturier** [comment]
Hello Nehon, i've made the changes needed in order to merge with the master. I think the problem are solved.

**Comment by Nehon** [comment]
Thanks you!

**Comment by jseinturier** [comment]
I'm sorry to have wasted your time ;-) I'm now writing a WIKI entry for the VR module, i've forked the wiki project from jMonkeyEngine and i will make a PR by the end of the week.

**Comment by Nehon** [comment]
Don't sweat it, you didn't waste my time :p 
By the way is there a VR example in jme-example project?

**Comment by jseinturier** [comment]
No, i've posted the example on the JMonkey forum as i did not want to add a dependency to the jme3-vr within the jme3-examples project. But if you authorize me to add such a dependency, i can commit the sample from the forum in to the jme3-examples project.

**Comment by empirephoenix** [comment]
Well I think it is no problem, as long as the other examples can be run no matter what the vr stuff does

**Comment by Nehon** [comment]
Yeah It could be nice to have a ready to go example for VR.

**Comment by jseinturier** [comment]
The sample is committed, i'm going to make the related PR but do i have to wait that this current PR is closed before the new one ?

**Comment by Nehon** [comment]
mhh seems it does not build
> Project with path ':jme3-vr' could not be found in project ':jme3-examples'.

**Comment by empirephoenix** [comment]
if (JavaVersion.current().isJava8Compatible()) {
    include 'jme3-lwjgl3'
    include 'jme3-vr'
}

you on java7? or travis?

**Comment by Nehon** [comment]
The log was from travis openjdk7 job.

**Comment by empirephoenix** [comment]
Hm maybe a new project for vr-examples / java8 examples is the better approach?

**Comment by Nehon** [comment]
ok the vr project  is java 8 only?

**Comment by jseinturier** [comment]
Yes the VR module needs lwjgl3 and java8

**Comment by Nehon** [comment]
oh ok so we can't use it in the example project then...
arf... it annoying...

**Comment by empirephoenix** [comment]
may i ask why do we support java7 currently? android stuff?

**Comment by Nehon** [comment]
Yep java8 is not supported on android.

**Comment by Nehon** [comment]
Maybe we should discuss this on the forum, and let other people chime in.

**Comment by jseinturier** [comment]
I've reverted the changes on the jme3-examples project (restored gradle file and removed vr related stuff)

**Comment by jseinturier** [comment]
I think it's ok now, the PR is correct.

**Comment by Nehon** [comment]
thanks

**Comment by ZNixian** [comment]
@jseinturier Just a heads-up for in future, 'Oculus' is spelt with a single 'c'.

**Comment by Nehon** [comment]
I've been caught thousand times by this one too...

**Pull request merged**
