### PR TITLE
Fixed #652

### LINKED ISSUE #652: Blender Importer - Generated textures with alpha have borders artifacts
When the importer get the textures from the blender file and set it to the model, it adds to these a gray "border". It doesn't add them, however, to the linkedData if **loadUnlinkedAssets** flag is set on the blender key.

It adds it too when "create j3m file" is selected on the sdk and the images are generated.

### PR DESCRIPTION
**Pull request by NemesisMate**
The issue was due to the texture blending with the object material. By default the material is gray (hence, a gray border). If the material color in blender is set to another color this is being the artifact's color. It can bee seen where the alpha in the texture isn't totally 0 or 1.
The current implementation weren't taking in account the material transparency when blending, so the fix is basically to use it just like blender does.

https://hub.jmonkeyengine.org/t/multiple-blender-importer-changes-fixes/38568

### CODE REVIEW

**Comment by empirephoenix** [comment]
Please close and open this, travis had some issues /home/travis/build/jMonkeyEngine/jmonkeyengine/jme3-blender/src/main/java/com/jme3/scene/plugins/blender/textures/blending/TextureBlenderAWT.java:240: error: cannot find symbol
                col = blendFactor * pixelColor[0];

Does this compile locally as it is in the git?

**Comment by NemesisMate** [comment]
Ok, I missed the var declaration. Fixed now.

**Comment by empirephoenix** [comment]
I'm still unsure about this (and the other blender related ones) on one side, I have no real way to confirm it is working, on the other hand, at least reading the code and the comment it makes sense to me. @Nehon what would your opinion be? just merge and see if complains happen?

**Comment by NemesisMate** [comment]
To check the issue with this one you can use the example .blend I submited for this [other issue](https://github.com/jMonkeyEngine/jmonkeyengine/pull/669).

You can see that when you generate it with the blender importer, a gray border is added to the generated texture.

**Pull request merged**
