### PR TITLE
fix errors in how vector projection is calculated

### PR DESCRIPTION
**Pull request by stephengold**
same diff I committed to 'master' on Jan 14, 2017
Without this change, the magnitude of the project() result is incorrect unless 'other' is a unit vector.

### CODE REVIEW

**Comment by Nehon** [comment]
mhhh....mhhh.... what with this line ending stuff?

**Comment by stephengold** [comment]
It's difficult for me to determine what's going on with the line endings. Not sure if it's my editor, my local repo, or GitHub that's changing them. But one of those three insists on adding carriage returns to Vector3f.java . Very embarrassing!

**Comment by empirephoenix** [comment]
Check your git settings, if you default install on windows for example it is set to replace stuff and modify it. Also check your favourite IDE, at east in eclipse you can set which line ending to use.

**Comment by stephengold** [comment]
"git config --get core.autocrlf" returns "true" for my repo. When I do "git config --list" on my repo, I don't see a setting for "core.autocrlf" so it's probably using the default, which for Windows7 is probably

**Comment by stephengold** [comment]
It turns out the value I wanted was "false". I'm ready to close this request and start a new one.

**Pull request closed without merging**
