### PR TITLE
Add missing @Override annotations

### PR DESCRIPTION
**Pull request by stephengold**

### CODE REVIEW

**Comment by MeFisto94** [comment]
Awesome! Thanks :)

**Comment by stephengold** [comment]
One sub-project done, 21 still to go...

**Comment by tonihele** [comment]
I added yesterday to Nifty subproject. Just didnt make PR. But encouraged
by this. Ill make one as soon as I get home.

Those and finals and some cleanup.

**Comment by stephengold** [comment]
Thanks Toni. I'll leave jme3-nifty in your hands, then.

**Comment by tonihele** [comment]
> 
> 
> Thanks Toni. I'll leave jme3-nifty in your hands, then.

https://github.com/jMonkeyEngine/jmonkeyengine/pull/1271 :)

**Comment by stephengold** [comment]
I believe this is ready for integration. If it's not integrated in 72 hours, I may do it myself.

**Pull request merged**
