### PR TITLE
resolve issue #1926 (unnecessary dependencies)

### PR DESCRIPTION
**Pull request by stephengold**
This modifies buildscripts to dodge some unnecessary dependencies.

### CODE REVIEW

**Comment by stephengold** [comment]
I believe this is ready to be integrated.

**Comment by Ali-RS** [comment]
Can we integrate this into the v3.6 branch via the GitHub web interface?

**Comment by stephengold** [comment]
I do all my cherry-picking using gitk. I've never done it using the GitHub web interface, and I'm not sure it's possible to do it that way.

**Comment by Ali-RS** [comment]
Ok, I was able to cherry-pick this PR into the v3.6 branch using the GitHub desktop app.

**Pull request merged**
