### PR TITLE
Solve #2136 (flow-control issue with glTF alpha parameter)

### LINKED ISSUE #2136: IllegalArgumentException while loading GLTF model
When I try to load [the "CesiumMan" model](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan/glTF) using [TestGltfLoading](https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-examples/src/main/java/jme3test/model/TestGltfLoading.java), I get an exception:

```console
Oct 28, 2023 6:55:20 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.7.0-SNAPSHOT
 * Branch: master
 * Git Hash: b86310b
 * Build Date: 2023-10-28
Oct 28, 2023 6:55:21 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 2.9.5 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jme3.util.ReflectionAllocator (file:/home/sgold/NetBeansProjects/jmonkeyengine/jme3-core/build/libs/jme3-core-3.7.0-SNAPSHOT.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.jme3.util.ReflectionAllocator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Oct 28, 2023 6:55:21 PM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: NVIDIA Corporation
 * Renderer: GeForce GT 545/PCIe/SSE2
 * OpenGL Version: 3.2.0 NVIDIA 390.157
 * GLSL Version: 1.50 NVIDIA via Cg compiler
 * Profile: Core
Oct 28, 2023 6:55:21 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.15.1
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
 * AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
Oct 28, 2023 6:55:21 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
Oct 28, 2023 6:55:21 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio effect extension version: 1.0
Oct 28, 2023 6:55:21 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 4
Oct 28, 2023 6:55:21 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.asset.AssetLoadException: An error occurred loading CesiumMan/glTF/CesiumMan.gltf
	at com.jme3.scene.plugins.gltf.GltfLoader.loadFromStream(GltfLoader.java:181)
	at com.jme3.scene.plugins.gltf.GltfLoader.load(GltfLoader.java:107)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:274)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:390)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:441)
	at jme3test.model.TestGltfLoading.loadModel(TestGltfLoading.java:234)
	at jme3test.model.TestGltfLoading.loadModel(TestGltfLoading.java:229)
	at jme3test.model.TestGltfLoading.simpleInitApp(TestGltfLoading.java:146)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:240)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:142)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:224)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Material parameter is not defined: alpha
	at com.jme3.material.Material.checkSetParam(Material.java:474)
	at com.jme3.material.Material.setParam(Material.java:490)
	at com.jme3.scene.plugins.gltf.MaterialAdapter.setParam(MaterialAdapter.java:106)
	at com.jme3.scene.plugins.gltf.GltfLoader.readMaterial(GltfLoader.java:660)
	at com.jme3.scene.plugins.gltf.GltfLoader.readMeshPrimitives(GltfLoader.java:473)
	at com.jme3.scene.plugins.gltf.GltfLoader.readNode(GltfLoader.java:252)
	at com.jme3.scene.plugins.gltf.GltfLoader.readChild(GltfLoader.java:301)
	at com.jme3.scene.plugins.gltf.GltfLoader.readChild(GltfLoader.java:309)
	at com.jme3.scene.plugins.gltf.GltfLoader.readChild(GltfLoader.java:309)
	at com.jme3.scene.plugins.gltf.GltfLoader.readScenes(GltfLoader.java:218)
	at com.jme3.scene.plugins.gltf.GltfLoader.loadFromStream(GltfLoader.java:155)
	... 11 more
```

I have reason to believe this is a recent regression. I'll attempt to pin it down.

### PR DESCRIPTION
**Pull request by tonihele**
Fixes #2136

### CODE REVIEW

**Comment by stephengold** [comment]
1. Have you tested this fix?
2. The refactoring is appreciated, but should probably go in a separate PR. Doing so much refactoring for a one-line fix obscures the fix.
3. I'm confused by the comment "// Alpha is a RenderState not a Material Parameter, so return null". It looks like "AlphaDiscardThreshold" *is* a material parameter. So why is it incorrect to return it?

**Comment by tonihele** [comment]
> 1. Have you tested this fix?
> 
>     2. The refactoring is appreciated, but should probably go in a separate PR. Doing so much refactoring for a one-line fix obscures the fix.
> 
>     3. I'm confused by the comment "// Alpha is a RenderState not a Material Parameter, so return null". It looks like "AlphaDiscardThreshold" _is_ a material parameter. So why is it incorrect to return it?

1. Yes, 3 different models I loaded.
2. I'll revert it and redo it without any refactoring. switch case is faster (marginally) and more readable (to me) but not worth a separate PR
3. The way this adapter pattern works here is that each implementation (here PBRMaterialAdapter) puts their own parameter mapping GLTF syntax -> jME x material syntax. This mapping then either works directly or some GLTF parameters are actually something else. With something else I mean RenderStates or somethings that require setting some other value. With other value, I guess one could create a new MatParam to return and have the super put it. But this would also be a refactor as the pattern in the file seems to be that the overrides are simply set there rather and a new MatParam created. I think it is clearer this current way.

I guess the correct comment would be something like `GLTF alpha mode already handled here, return null`. Returning null means that the super doesn't set it anymore.

**Comment by stephengold** [comment]
Thanks for the answers. I'll delay integration so you can address items 2 and 3.

**Comment by tonihele** [comment]
Less invasive patch implemented

**Comment by stephengold** [comment]
Thanks, @tonihele. Unless there's substantial discussion, I plan to integrate this in about 48 hours.

**Pull request merged**
