### PR TITLE
Add tests for com.jme3.math.FastMath

### PR DESCRIPTION
**Pull request by James-Adam**
Hi, 
I've analysed your code base and noticed that `com.jme3.math.FastMath` is not fully tested.

I've written some tests for the functions in this class with the help of [Diffblue](https://www.diffblue.com/) [Cover](https://www.diffblue.com/products). Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.

### CODE REVIEW

**Comment by stephengold** [comment]
This looks fine.  Thank you.  I'll leave this PR open a few days in case someone else wants to review it.

I'm a little surprised your efforts didn't uncover any bugs in `FastMath`.

If you're interested in writing more tests, I suggest you look next at the `com.jme3.math.Vector3f` class, the `com.jme3.renderer.Camera` class, or the `com.jme3.scene` package. But if you're anything like me, you'll find room for improvement almost anywhere you look.

**Comment by Ali-RS** [comment]
Also include this package if you are interested `com.jme3.anim`  in jme3-core module :
https://github.com/jMonkeyEngine/jmonkeyengine/tree/master/jme3-core/src/main/java/com/jme3/anim

**Comment by James-Adam** [comment]
I'm happy to contribute!

I'm very interested at taking a look at some of the classes/packages suggested, and will be looking to have tests for these written over the next few days. 
I am specifically taking a look at `com.jme3.math.Vector3f` currently; this class is around 50% covered as it stands currently, but with no dedicated tests. @stephengold Would you be interested in seeing a new test class written to cover as much of this class as possible regardless of which methods are covered serendipitously by other test classes, or would you prefer tests which cover only the uncovered lines?

**Comment by stephengold** [comment]
Uncovered code paths should take priority. But I wouldn't object to being systematic and thorough unless/until testing has a noticeable impact on the build process.

**Comment by stephengold** [comment]
By the way, the fields of a `Vector3f` are public, so it's never necessary to use `Vector3f.getX()` or `Vector3f.getY()` or `Vector3f.getZ()`.

**Pull request merged**
