### PR TITLE
Lights : added light v. sphere intersection

### PR DESCRIPTION
**Pull request by Dokthar**
- implementations of intersectsSphere() for Ambient / Directional / Point / Spot  Light
(see #362)

### CODE REVIEW

**Comment by shadowislord** [comment]
We have some unit tests for the light culling here:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/test/java/com/jme3/light/LightFilterTest.java

Could you include a test case for a model which uses a bounding sphere?

**Comment by Dokthar** [comment]
Yes, i'll add this when i have time.

**Comment by Dokthar** [comment]
I could also move the code for collision of sphere v. sphere (and v. cone) into Intersection.java , what do you think ?

**Comment by shadowislord** [comment]
@Dokthar If you think it makes sense to share that code between bounding volumes and lights then go ahead.

**Comment by Dokthar** [comment]
@shadowislord I agree that's feel strange to put the sphere v. cone collision code inside Intersection, as it's need a lot of parameters (already computed inside the cone light). 
Also I found that the collision code used for sphere v. sphere was already wrote (inside Intersection), so i use this one.

**Comment by Dokthar** [comment]
Don't merge this yet, one test case is wrong, i am trying to fix this.

**Comment by Dokthar** [comment]
@shadowislord : I don't have more changes comming so you can review this.

**Pull request merged**
