### PR TITLE
Fixed settings of shadow render2

### PR DESCRIPTION
**Pull request by JavaSaBr**
Fixed 2 parameters of shadow renderer.

### CODE REVIEW

**Comment by JavaSaBr** [comment]
@Nehon any news?

**Comment by Nehon** [comment]
Sorry slipped my mind

**Comment by pspeed42** [comment]
This would potentially break applications relying on the old unmultiplied behavior.  Best for 3.3 and not 3.2.2.

**Comment by pspeed42** [comment]
I didn't change the tag of anything.  I changed the milestone marker that sgold is using to see what should go into 3.2.2.  The code was merged to master.  sgold is trying to figure out what to merge to the 3.2.x branch for 3.2.2.  Since this code might break an existing 3.2.1 application then this should not go into 3.2.2.

**Pull request merged**
