### PR TITLE
Migrate TestSpatialAnim to the new Anim class

### PR DESCRIPTION
**Pull request by syluna**
Remove all deprecated class and migrate to the new animation system.

### CODE REVIEW

**Comment by Ali-RS** [comment]
Thanks for PR.

It probably would be better to have both. You can separate them in two methods, `testUsingOldAnimationSystem`, `testUsingNewAnimationSystem` and by default set it to use the new animation system.

**Comment by oxplay2** [comment]
are you sure, that we should have Deprecated animation system tests in 3.3+?

**Comment by Ali-RS** [comment]
Yes, I think until the old animation system is not removed we should keep it's tests also. When we removed it the we can remove it's tests as well. This is just my opinion, so let's see what others think.

**Comment by oxplay2** [comment]
Paul and Darkchaos agreed on discord to keep only 3.3 related tests in 3.3+

reasons:
- encourage people to use new due to find all issues that left.(bug finding)
- people can anyway browse old tests

**Comment by Ali-RS** [comment]
Okay, fine then.

**Comment by pspeed42** [comment]
Yeah, specifically if the old tests start to disappear maybe folks reluctant to move for "some reason" will start panicking and making those reasons well known.

And from experience in my day job, if you leave bad code laying around, someone will cut and paste it into new code.  It propagates like a virus sometimes. :)

**Comment by stephengold** [comment]
Not providing tests/examples for deprecated methods is fine by me.

Thank you for your contribution, @syluna!

**Comment by stephengold** [comment]
Included in v3.3 branch at 68c6f71

**Pull request merged**
