### PR TITLE
Fixed NPE and ConcurrentModificationException

### PR DESCRIPTION
**Pull request by JavaSaBr**
Fixed NPE and ConcurrentModificationException during cloning TechniqeDef.

### CODE REVIEW

**Comment by JavaSaBr** [comment]
@Nehon @empirephoenix could you review this, please?

**Comment by empirephoenix** [comment]
as far I understand this, before they had shared lists between them? makes sense to create new ones then.

**Comment by JavaSaBr** [comment]
@empirephoenix in the case with ShaderGenerationInfo, I had the same instances of lists in original ShaderGenerationInfo and in cloned version.

**Comment by Nehon** [comment]
mhh that's weird I never had this issue....
Anyway yeah they should be cloned

**Pull request merged**
