### PR TITLE
[M]Fix issue#1436

### PR DESCRIPTION
**Pull request by jmecn**
Fix the code error when checking UTF-8 data

let content = [0xE4, 0x8A, 0xBC], let `b = 0xE4` (1110 0100)

See this part:
````java
                if (b < 0x80) {
                    // good
                }
                else if ((b & 0xC0) == 0xC0) {//   (0xE4 & 0xC0) == 0xC0     =====>  true
                    utf8State = UTF8_2BYTE;
                }
                else if ((b & 0xE0) == 0xE0) {//   (0xE4 & 0xE0) == 0xE0      =====>  true
                    utf8State = UTF8_3BYTE_1;
                }
                else {
                    utf8State = UTF8_ILLEGAL;
                }
````

3 bytes UTF-8 data while always be treated as 2 bytes UTF-8 data.

### CODE REVIEW

**Comment by stephengold** [comment]
Please change "is" to "are" in 3 places. Other than that, this looks great.

**Comment by jmecn** [comment]
It looks better that always treat String data as UTF-8.
write it UTF-8, read it UTF-8

see https://hub.jmonkeyengine.org/t/code-error-on-checking-utf-8-data/43909

**Comment by riccardobl** [comment]
Can you use StandardCharsets.UTF_8 for the charset?

**Comment by jmecn** [comment]
> Can you use StandardCharsets.UTF_8 for the charset?

OK, but it's better to use it in both input and output.

https://github.com/jMonkeyEngine/jmonkeyengine/blob/2196e4c/jme3-core/src/plugins/java/com/jme3/export/binary/BinaryOutputCapsule.java#L688

**Review by riccardobl — APPROVED** [review]
Perfect.

**Pull request merged**
