### PR TITLE
Implemented auto free LWJGL byte buffers.

### PR DESCRIPTION
**Pull request by JavaSaBr**
Implemented auto free LWJGL byte buffers.

### CODE REVIEW

**Comment by empirephoenix** [comment]
Thanks, I merged it without further testing, after all, it can't be any worse than the state before :)

**Comment by JavaSaBr** [comment]
Thanks, I did some tests, it works fine.

**Comment by AlrikG** [comment]
sounds good, but what was the purpose to replace this one?

- return MemoryUtil.memAlloc(size);
+final Long address = MemoryUtil.nmemAlloc(size);
+final ByteBuffer byteBuffer = MemoryUtil.memByteBuffer(address, size);

**Comment by JavaSaBr** [comment]
What do you mean?

**Comment by AlrikG** [comment]
I saw in the changes that you replaced "return MemoryUtil.memAlloc(size);" by the two new lines by I don't get it why did you do that. Is there any special reason for that? Don't get me wrong it is just out of interest :D

**Comment by JavaSaBr** [comment]
I need to get address of allocated memory to make a deallocator.
http://imgur.com/a/wV43x

**Comment by AlrikG** [comment]
ah ups my bad xD ... thanks for this PR :)

**Comment by Ali-RS** [comment]
Thank you @JavaSaBr  :+1:

**Comment by zzuegg** [comment]
IMHO it would be nice to have at least the possibility to manage the cleaning up myself. Like calling BufferAllocator.cleanup() myself rather then having a uncontrollable deamon.

**Comment by JavaSaBr** [comment]
You have the method:  BufferUtils.destroyDirectBuffer(data);

**Comment by empirephoenix** [comment]
It's no daemon, its the GC, it behaves similarly to the normal collections of the default BufferUtil

**Comment by zzuegg** [comment]
Well, its not the GC, its clearly a deamon thread deallocating the native memory. It does behave similar to the default BufferUtil, and it is also fine that this is the default. But since we are tracking the objects it would be nice offer the possiblity of manual destruction without the need of tracking the buffer usages myself. Like combining the best of both worlds, mindless allocating/nulling and beeing able to trigger the cleanup at a time i know it will not jitter my frametimes.

**Comment by zzuegg** [comment]
Maybe out of scope of this PR..

**Comment by JavaSaBr** [comment]
If you will use BufferUtils.destroyDirectBuffer(), this "deamon" will skip these buffers.

**Comment by empirephoenix** [comment]
You know how it goes :) WE are happy to hear from your PR :)

**Pull request merged**
