### PR TITLE
solve issue #2007 (instanced objects are culled when using WaterFilter)

### PR DESCRIPTION
**Pull request by Ali-RS**
Solves https://github.com/jMonkeyEngine/jmonkeyengine/issues/2007

The issue is that InstancedGeometry uses the wrong camera for "instance culling" check when rendering the scene from multiple viewports (e.g. main viewport and water reflection viewport) and this causes objects to get culled wrongly.

It is because `InstancedGeometry.updateInstances()` use the old camera (from the previous viewport) before it is updated in the below method:

https://github.com/jMonkeyEngine/jmonkeyengine/blob/25a3407c9e403dbc0250430a304031c169636a03/jme3-core/src/main/java/com/jme3/scene/instancing/InstancedGeometry.java#L420-L423

this PR changed the code so it passes the camera into `updateInstances()` by the caller method.

Because `updateInstances()` is a `public` method on InstancedGeometry (not sure why it is so?) this PR should be considered a breaking change I believe because the method signature is changed!

### CODE REVIEW

**Comment by stephengold** [comment]
Yes it's a breaking change. No, I don't know why the method is `public`.

**Comment by Ali-RS** [comment]
Unless there's something to discuss, I plan to self-integrate this PR in about 24 hours.

**Comment by Ali-RS** [comment]
We might want to consider this for 3.6.1 (even if a breaking change), because

1- the bug is important enough 
2- this won't affect 99% of JME apps in a bad way I believe, because `updateInstances()` is not meant to be called by user code.

**Comment by stephengold** [comment]
I'm willing to consider this for 3.6.1, but I'm not convinced. To me, the issue looks like a corner case. What percentage of JME apps do you imagine combine instanced objects with a WaterFilter?

**Comment by Ali-RS** [comment]
>What percentage of JME apps do you imagine combine instanced objects with a WaterFilter?

Note, this is not just about the water filter, but any case that a scene is rendered by multiple viewports. The water filter is just an example of such a case.

**Comment by stephengold** [comment]
In that case I would expect shadow filters to be affected, which greatly raises the priority of this fix.

Still, I can't see myself listing "breaking changes" in the release notes for a patch. Isn't there *any* way to solve #2007 without introducing a breaking change?

**Comment by Ali-RS** [comment]
>I would expect shadow filters to be affected,

Seems this does not affect the shadow filter because it does not call `RenderManager.renderScene()` and so `Spatial.checkCulling(Camera cam)` is not called.

**Comment by stephengold** [comment]
It seems to me that with the following additional changes, this PR would no longer be a breaking change:

```diff
--- a/jme3-core/src/main/java/com/jme3/scene/instancing/InstancedGeometry.java
+++ b/jme3-core/src/main/java/com/jme3/scene/instancing/InstancedGeometry.java
@@ -75,6 +75,7 @@ public class InstancedGeometry extends Geometry {
 
     private int firstUnusedIndex = 0;
     private int numVisibleInstances = 0;
+    private Camera cam;
 
     public InstancedGeometry() {
         super();
@@ -275,6 +276,13 @@ public class InstancedGeometry extends Geometry {
         }
     }
 
+    /**
+     * @Deprecated use {@link #updateInstances(com.jme3.renderer.Camera)
+     */
+    public void updateInstances() {
+        updateInstances(cam);
+    }
+
     public void updateInstances(Camera cam) {
         FloatBuffer fb = (FloatBuffer) transformInstanceData.getData();
         fb.limit(fb.capacity());
@@ -415,6 +423,12 @@ public class InstancedGeometry extends Geometry {
         allInstanceData = allData.toArray(new VertexBuffer[allData.size()]);
     }
 
+    @Override
+    public boolean checkCulling(Camera cam) {
+        this.cam = cam;
+        return super.checkCulling(cam);
+    }
+
     @Override
     public int collideWith(Collidable other, CollisionResults results) {
         return 0; // Ignore collision
```

**Comment by stephengold** [comment]
PR #2036 makes this not a breaking change, so it will be included in v3.6.1 .

**Pull request merged**
