### PR TITLE
Ogre importer ignores receive_shadows  issue #647

### PR DESCRIPTION
**Pull request by thoced**
The receive_shadow flag is normally interpreted.
Thoced

### CODE REVIEW

**Comment by Nehon** [comment]
@stephengold is it ok for you?

**Comment by stephengold** [comment]
The code looks plausible. Has the change been tested?

**Comment by thoced** [comment]
yes I tested, the shadowmode is well applied to materials

**Comment by stephengold** [comment]
This morning it occurred to me that RenderQueue.ShadowMode.Receive might not be the best setting for a model, since it doesn't include the capability to cast shadows.

**Comment by thoced** [comment]
Indeed, the problem is that the OgreScript does not export a flag to indicate that we want to project shadows.

We could force with the ShadowMode.CastAndReceive parameter but that would not be correct either if the user does not want the shadow to be projected.

Maybe we should look in the Blender ogre export script and add this possibility

**Comment by stephengold** [comment]
An excellent idea.

**Comment by stephengold** [comment]
And thank you, @thoced for your contribution to the project!

**Comment by Nehon** [comment]
IMO it's lot of work for not that much. The user can easily fix this issue in the engine once the model is loaded.

**Pull request merged**
