### PR TITLE
Added a (hacky) fix for a Java Swing/AWT + GLFW interaction issue…

### PR DESCRIPTION
**Pull request by Ali-RS**
… on Linux.

Read more on https://hub.jmonkeyengine.org/t/experimenting-lwjgl3/37275

### CODE REVIEW

**Comment by Ali-RS** [comment]
@empirephoenix  any thought ?

**Comment by empirephoenix** [comment]
I had the BadRenderer issue a lot of times in smaller Tests, but never in my full Application, this would explain this. While this is extremly ugly, if it makes stuff work 99% of the time it is still a great improvement. So from my point of view this might be ok. Might another approch be, to drain the XWindow error queue on JME-LWJGL3 init?

**Comment by empirephoenix** [comment]
Thanks for investigating this

**Comment by Ali-RS** [comment]
@empirephoenix  thanks for merging it. 

Regarding 

> Might another approch be, to drain the XWindow error queue on JME-LWJGL3 init?

I took a look at it but was unable to understand what is going on there. Sorry about that :( 

I just clone this PR from what @Renanse  did in this PR : https://github.com/Renanse/Ardor3D/commit/3984929e9763f2e80bcbac04f875912e00a26086

**Comment by stephengold** [comment]
Is this fix suitable for JME v3.2.2 ?

**Comment by Ali-RS** [comment]
Don't see any strong reason why it should not be :)

**Pull request merged**
